(()=>{
if(typeof map==='undefined'||!map.pm)return;
const q=s=>document.querySelector(s),R=6371008.8,CENT_M2=40.468564224,labels=L.layerGroup([], {pmIgnore:true}).addTo(map);let selected=null,labelsOn=false,loading=false,lastError='';
function shapeOf(l){try{return l?.options?.tagroShape||(l?.pm&&l.pm.getShape?l.pm.getShape():null)||''}catch(e){return''}}
function identityName(l){const id=l?.options?.tagroIdentityId;if(!id)return'Unidentified';const b=document.querySelector(`[data-tagro-id="${CSS.escape(id)}"]`);return b?b.textContent.trim():id}
function ll(v){return v&&typeof v.lat==='number'?v:null}
function firstRing(v){if(!Array.isArray(v))return[];if(v.length&&ll(v[0]))return v;for(const x of v){const r=firstRing(x);if(r.length)return r}return[]}
function pointsOf(l){if(!l)return[];if(l instanceof L.Circle)return[l.getLatLng()];if(l instanceof L.Marker||l instanceof L.CircleMarker)return[l.getLatLng()];if(l.getLatLngs)return firstRing(l.getLatLngs());return[]}
function rad(x){return x*Math.PI/180}function deg(x){return x*180/Math.PI}
function dist(a,b){return map.distance(a,b)}
function bearing(a,b){const p1=rad(a.lat),p2=rad(b.lat),d=rad(b.lng-a.lng),y=Math.sin(d)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(d);return(deg(Math.atan2(y,x))+360)%360}
const dirs=['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'];function compass(b){return dirs[Math.round(((b%360)+360)%360/22.5)%16]}
function fmtM(v){if(!Number.isFinite(v))return'—';return(v>=100? v.toFixed(1):v.toFixed(2))+' m'}
function fmtArea(v){if(!Number.isFinite(v))return'—';return v>=10000?(v/10000).toFixed(3)+' ha':v.toFixed(1)+' m²'}
function closeRing(p){if(p.length<2)return p.slice();const a=p[0],b=p[p.length-1];return Math.abs(a.lat-b.lat)<1e-10&&Math.abs(a.lng-b.lng)<1e-10?p.slice():[...p,a]}
function lengthOf(p,closed=false){const a=closed?closeRing(p):p;let n=0;for(let i=1;i<a.length;i++)n+=dist(a[i-1],a[i]);return n}
function areaOf(p){if(p.length<3)return 0;const lat0=rad(p.reduce((s,x)=>s+x.lat,0)/p.length),xy=p.map(x=>({x:R*rad(x.lng)*Math.cos(lat0),y:R*rad(x.lat)}));let a=0;for(let i=0,j=xy.length-1;i<xy.length;j=i++)a+=xy[j].x*xy[i].y-xy[i].x*xy[j].y;return Math.abs(a)/2}
function orientation(p){if(p.length<2)return null;if(p.length===2)return bearing(p[0],p[1]);const lat0=rad(p.reduce((s,x)=>s+x.lat,0)/p.length),xy=p.map(x=>({x:R*rad(x.lng)*Math.cos(lat0),y:R*rad(x.lat)}));const mx=xy.reduce((s,v)=>s+v.x,0)/xy.length,my=xy.reduce((s,v)=>s+v.y,0)/xy.length;let xx=0,yy=0,xyc=0;xy.forEach(v=>{const x=v.x-mx,y=v.y-my;xx+=x*x;yy+=y*y;xyc+=x*y});const theta=.5*Math.atan2(2*xyc,xx-yy);return(90-deg(theta)+360)%180}
function measurement(l){if(!l)return null;const s=shapeOf(l),p=pointsOf(l),id=l.options.tagroIdentityId||null;if(l instanceof L.Circle){const r=l.getRadius();return{kind:'circle',shape:s,identity:id,center:l.getLatLng(),radius:r,diameter:2*r,circumference:2*Math.PI*r,area:Math.PI*r*r,bearing:null,elevationPoints:[l.getLatLng()]}}
if(l instanceof L.Marker||l instanceof L.CircleMarker||s==='Marker'||s==='CircleMarker'||s==='Text'){const x=l.getLatLng();return{kind:'point',shape:s,identity:id,point:x,bearing:null,elevationPoints:[x]}}
if(s==='Polygon'||s==='Rectangle'){const ring=firstRing(l.getLatLngs()),a=areaOf(ring),per=lengthOf(ring,true),b=orientation(ring);return{kind:'boundary',shape:s,identity:id,points:ring,area:a,perimeter:per,bearing:b,elevationPoints:ring}}
const len=lengthOf(p,false),b=p.length>1?bearing(p[0],p[p.length-1]):null;return{kind:'line',shape:s,identity:id,points:p,length:len,bearing:b,elevationPoints:p.length>1?[p[0],p[p.length-1]]:p}}
function elevMeta(l){return l.options.tagroElevation||(l.options.tagroElevation={provider:'Open-Meteo / Copernicus DEM 90m',map:null,mapStale:false,survey:[],accepted:'map'})}
function fingerprint(points){return points.map(p=>`${p.lat.toFixed(7)},${p.lng.toFixed(7)}`).join('|')}
async function fetchElevation(points){const out=[];for(let i=0;i<points.length;i+=100){const c=points.slice(i,i+100),lat=c.map(x=>x.lat.toFixed(7)).join(','),lon=c.map(x=>x.lng.toFixed(7)).join(',');const r=await fetch(`https://api.open-meteo.com/v1/elevation?latitude=${encodeURIComponent(lat)}&longitude=${encodeURIComponent(lon)}`);if(!r.ok)throw new Error('Elevation service unavailable');const d=await r.json();if(!Array.isArray(d.elevation))throw new Error(d.reason||'No elevation returned');out.push(...d.elevation.map(Number))}return out}
function currentElev(m,meta){const mapVals=Array.isArray(meta.map)?meta.map:[],survey=Array.isArray(meta.survey)?meta.survey:[];if(meta.accepted==='survey'&&survey.length){if(m.kind==='point'&&Number.isFinite(survey[0]))return{source:'Surveyed',values:[survey[0]]};if(m.kind==='line'&&Number.isFinite(survey[0])&&Number.isFinite(survey[1]))return{source:'Surveyed',values:[survey[0],survey[1]]}}return mapVals.length?{source:'Map terrain',values:mapVals}:null}
function clearLabels(){labels.clearLayers();labelsOn=false}
function mid(a,b){return L.latLng((a.lat+b.lat)/2,(a.lng+b.lng)/2)}
function addLabel(a,b,index){const d=dist(a,b),br=bearing(a,b),html=`<div class="tagro-measure-label">${index?index+' · ':''}${fmtM(d)} <span class="dir">${compass(br)} ${br.toFixed(0)}°</span></div>`;L.marker(mid(a,b),{interactive:false,pmIgnore:true,icon:L.divIcon({className:'',html,iconAnchor:[0,0]})}).addTo(labels)}
function showSegments(l){clearLabels();if(!l)return;const m=measurement(l);if(!m)return;if(m.kind==='line'){for(let i=1;i<m.points.length;i++)addLabel(m.points[i-1],m.points[i],i)}else if(m.kind==='boundary'){const r=closeRing(m.points);for(let i=1;i<r.length;i++)addLabel(r[i-1],r[i],i)}labelsOn=labels.getLayers().length>0;render(l)}
function elevSummary(m,meta){const c=currentElev(m,meta);if(!c)return null;const v=c.values.filter(Number.isFinite);if(!v.length)return null;if(m.kind==='point')return{source:c.source,text:`${v[0].toFixed(1)} m`,values:v};if(m.kind==='line'&&v.length>=2){const delta=v[1]-v[0];return{source:c.source,text:`${v[0].toFixed(1)} → ${v[1].toFixed(1)} m`,delta,values:v}}return{source:c.source,text:`${Math.min(...v).toFixed(1)} – ${Math.max(...v).toFixed(1)} m`,delta:Math.max(...v)-Math.min(...v),values:v}}
function cards(m){if(m.kind==='point')return`<div class="tagro-measure-card wide"><span>Position</span><b>${m.point.lat.toFixed(6)}, ${m.point.lng.toFixed(6)}</b></div>`;if(m.kind==='circle')return`<div class="tagro-measure-card"><span>Radius</span><b>${fmtM(m.radius)}</b></div><div class="tagro-measure-card"><span>Diameter</span><b>${fmtM(m.diameter)}</b></div><div class="tagro-measure-card"><span>Circumference</span><b>${fmtM(m.circumference)}</b></div><div class="tagro-measure-card"><span>Area</span><b>${fmtArea(m.area)}</b></div>`;if(m.kind==='boundary')return`<div class="tagro-measure-card"><span>Area</span><b>${fmtArea(m.area)}</b></div><div class="tagro-measure-card"><span>Area · cents</span><b>${(m.area/CENT_M2).toFixed(3)}</b></div><div class="tagro-measure-card"><span>Perimeter</span><b>${fmtM(m.perimeter)}</b></div><div class="tagro-measure-card"><span>Orientation</span><b>${m.bearing===null?'—':compass(m.bearing)+' '+m.bearing.toFixed(0)+'°'}</b></div>`;return`<div class="tagro-measure-card"><span>Total length</span><b>${fmtM(m.length)}</b></div><div class="tagro-measure-card"><span>Direction</span><b>${m.bearing===null?'—':compass(m.bearing)+' '+m.bearing.toFixed(0)+'°'}</b></div>`}
function elevationBox(l,m){const meta=elevMeta(l),e=elevSummary(m,meta),stale=meta.mapStale?' · refresh needed':'';let survey='';if(m.kind==='point')survey=`<div class="tagro-elev-row"><label>Surveyed elevation (m)</label><input id="measureSurvey0" type="number" step="0.01" value="${Number.isFinite(meta.survey?.[0])?meta.survey[0]:''}" placeholder="RL"></div>`;else if(m.kind==='line')survey=`<div class="tagro-elev-row"><label>Survey start (m)</label><input id="measureSurvey0" type="number" step="0.01" value="${Number.isFinite(meta.survey?.[0])?meta.survey[0]:''}" placeholder="RL"></div><div class="tagro-elev-row"><label>Survey end (m)</label><input id="measureSurvey1" type="number" step="0.01" value="${Number.isFinite(meta.survey?.[1])?meta.survey[1]:''}" placeholder="RL"></div>`;const surveyReady=m.kind==='point'?Number.isFinite(meta.survey?.[0]):m.kind==='line'?Number.isFinite(meta.survey?.[0])&&Number.isFinite(meta.survey?.[1]):false;return`<div class="tagro-elev-box"><div class="tagro-elev-head"><b>Elevation</b><button id="measureLoadElev" class="tagro-measure-btn" ${loading?'disabled':''}>${loading?'Loading…':meta.map?'Refresh map':'Load map'}</button></div><div class="tagro-measure-grid"><div class="tagro-measure-card wide"><span>Map terrain${stale}</span><b>${meta.map&&meta.map.length?elevSummary(m,{...meta,accepted:'map'})?.text||'—':'Not loaded'}</b></div>${e?`<div class="tagro-measure-card wide"><span>Accepted · ${e.source}</span><b>${e.text}${Number.isFinite(e.delta)?` · ${e.delta>=0?'rise':'fall'} ${Math.abs(e.delta).toFixed(1)} m`:''}</b></div>`:''}</div>${survey}<div class="tagro-elev-row"><label>Use for calculations</label><select id="measureElevSource"><option value="map" ${meta.accepted!=='survey'?'selected':''}>Map terrain</option><option value="survey" ${meta.accepted==='survey'?'selected':''} ${surveyReady?'':'disabled'}>Surveyed</option></select></div><div class="tagro-elev-source">Map terrain is an estimate from Open-Meteo / Copernicus DEM at about 90 m resolution. Surveyed values are kept separately and never overwrite the map value.</div>${m.kind==='boundary'?'<div class="tagro-measure-status">Survey contours / RL points can later populate this boundary from the uploaded survey or CAD file.</div>':''}${lastError?`<div class="tagro-measure-error">${lastError}</div>`:''}</div>`}
function wireElevation(l,m){const meta=elevMeta(l),btn=q('#measureLoadElev');if(btn)btn.onclick=async()=>{lastError='';loading=true;render(l);try{meta.map=await fetchElevation(m.elevationPoints);meta.mapCoords=fingerprint(m.elevationPoints);meta.mapStale=false}catch(e){lastError=e.message||'Elevation could not be loaded'}finally{loading=false;render(l)}};['0','1'].forEach(i=>{const el=q('#measureSurvey'+i);if(el)el.onchange=()=>{meta.survey=Array.isArray(meta.survey)?meta.survey:[];const v=parseFloat(el.value);meta.survey[+i]=Number.isFinite(v)?v:null;const ready=m.kind==='point'?Number.isFinite(meta.survey[0]):Number.isFinite(meta.survey[0])&&Number.isFinite(meta.survey[1]);if(!ready&&meta.accepted==='survey')meta.accepted='map';render(l)}});const src=q('#measureElevSource');if(src)src.onchange=()=>{meta.accepted=src.value;render(l)}}
function render(l=selected){selected=l||null;const pane=q('#cadMeasure');if(!pane)return;clearLabelsIfWrong();if(!selected){pane.innerHTML='<div class="tagro-measure-empty">Select a drawn object, then open Measure. Measurements always come from that same map geometry.</div>';return}const m=measurement(selected);if(!m){pane.innerHTML='<div class="tagro-measure-empty">This object has no measurable geometry.</div>';return}const br=m.bearing??0,sub=m.kind==='boundary'?'Field / boundary':m.kind==='line'?'Line / pipe':m.kind==='point'?'Point':m.kind==='circle'?'Circle':m.shape;pane.innerHTML=`<div class="tagro-measure"><div class="tagro-compass-row"><div class="tagro-compass"><span class="n">N</span><span class="e">E</span><span class="s">S</span><span class="w">W</span><i class="tagro-compass-arrow" style="--bearing:${br}deg"></i></div><div class="tagro-measure-title"><b>${identityName(selected)}</b><span>${sub}${m.bearing===null||m.bearing===undefined?'':` · ${compass(m.bearing)} ${m.bearing.toFixed(0)}°`}</span></div></div><div class="tagro-measure-grid">${cards(m)}</div>${(m.kind==='line'||m.kind==='boundary')?`<div class="tagro-measure-actions"><button id="measureSegments" class="tagro-measure-btn ${labelsOn?'on':''}">${labelsOn?'Hide':'Show'} ${m.kind==='boundary'?'sides':'segments'}</button></div>`:''}${elevationBox(selected,m)}</div>`;const seg=q('#measureSegments');if(seg)seg.onclick=()=>labelsOn? (clearLabels(),render(selected)):showSegments(selected);wireElevation(selected,m)}
function clearLabelsIfWrong(){if(!labelsOn)return;if(!selected)clearLabels()}
function invalidate(l){if(!l)return;const meta=elevMeta(l);if(meta.map){meta.mapStale=true}if(l===selected){clearLabels();render(l)}}
window.addEventListener('tagro:cadselect',e=>{selected=e.detail?.layer||null;clearLabels();if(q('#cadMeasure')?.classList.contains('on'))render(selected)});
window.addEventListener('tagro:cadchange',e=>invalidate(e.detail?.layer));
window.addEventListener('tagro:identitychange',e=>{if(e.detail?.layer===selected&&q('#cadMeasure')?.classList.contains('on'))render(selected)});
map.on('pm:remove',e=>{if(e.layer===selected){selected=null;clearLabels();render(null)}});
window.TAGRO_MEASURE={measure:measurement,render,clearLabels,fetchElevation,invalidate,getSelected:()=>selected};
})();