(()=>{
function boot(){if(!window.TAGRO_CAD||!window.TAGRO_HYDRAULICS)return setTimeout(boot,80);const tabs=document.querySelector('.tagro-cad-tabs'),dock=document.querySelector('.tagro-cad');if(!tabs||document.querySelector('[data-cad-tab="engineering"]'))return;tabs.style.gridTemplateColumns='repeat(4,1fr)';const b=document.createElement('button');b.className='tagro-cad-tab';b.dataset.cadTab='engineering';b.textContent='Design';tabs.appendChild(b);const pane=document.createElement('div');pane.id='cadEngineering';pane.className='tagro-cad-pane';dock.appendChild(pane);let active=false;
function selected(){return window.TAGRO_CAD.getSelected?.()||null}function role(l){const r=l?.options?.tagroIdentityId;return['main','submain','lateral'].includes(r)?r:null}function eng(l){const r=role(l);const defaults=r==='main'?{size:50,material:'PVC',sdr:13.6}:r==='submain'?{size:40,material:'PVC',sdr:13.6}:{size:16,material:'LLDPE',sdr:13.6};return l.options.tagroEngineering||(l.options.tagroEngineering=defaults)}
function acceptedElev(l){const x=l?.options?.tagroElevation||{},survey=Array.isArray(x.survey)?x.survey:[],map=Array.isArray(x.map)?x.map:[];if(x.accepted==='survey'&&Number.isFinite(survey[0])&&Number.isFinite(survey[1]))return{source:'Surveyed',start:survey[0],end:survey[1]};if(Number.isFinite(map[0])&&Number.isFinite(map[1]))return{source:'Map terrain',start:map[0],end:map[1]};return null}
function sizes(r){return r==='lateral'?[12,16,20]:[25,32,40,50,63,90]}
function render(){if(!active)return;const l=selected();if(!l){pane.innerHTML='<div class="tagro-eng-empty">Select a Main, Submain or Lateral to engineer it.</div>';return}const r=role(l);if(!r){pane.innerHTML='<div class="tagro-eng-empty">Identify this line as Main, Submain or Lateral first.</div>';return}const m=window.TAGRO_MEASURE?.measure?.(l),e=acceptedElev(l),g=eng(l),len=m?.length||0;let result=null;if(e){try{result=window.TAGRO_HYDRAULICS.evaluatePipe({role:r,nominalMm:g.size,lengthM:len,startElevationM:e.start,endElevationM:e.end,sdr:g.sdr})}catch(err){}}
pane.innerHTML=`<div class="tagro-eng"><div class="tagro-eng-title"><b>${r[0].toUpperCase()+r.slice(1)}</b><span>${len.toFixed(2)} m${e?' · '+e.source:' · elevation required'}</span></div><div class="tagro-eng-row"><label>Pipe size</label><select id="engSize">${sizes(r).map(x=>`<option value="${x}" ${+g.size===x?'selected':''}>${x} mm</option>`).join('')}</select></div><div class="tagro-eng-row"><label>Material</label><select id="engMaterial">${(r==='lateral'?['LLDPE']:['PVC','HDPE','Oval Hose']).map(x=>`<option ${g.material===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="tagro-eng-row"><label>SDR / design ratio</label><input id="engSdr" type="number" min="1" step="0.1" value="${g.sdr}"></div>${result?`<div class="tagro-eng-grid"><div><span>Rise / fall</span><b>${result.riseM>=0?'Rise ':'Fall '}${Math.abs(result.riseM).toFixed(2)} m</b></div><div><span>Grade</span><b>${result.gradePct.toFixed(2)}%</b></div><div><span>Effective head</span><b>${result.effectiveHeadM.toFixed(2)} m</b></div><div><span>Hydraulic status</span><b>${result.headStatus}</b></div><div><span>K · base</span><b>${result.baseK.toFixed(2)}</b></div><div><span>K · terrain</span><b>${result.terrainAdjustedK.toFixed(2)}</b></div><div class="wide"><span>Laminar permissible length</span><b>${result.laminarPermissibleM.toFixed(2)} m</b></div></div>`:`<div class="tagro-eng-note">Load map elevation in Measure, or enter surveyed start/end RL, to run the terrain-aware hydraulic check.</div>`}<div class="tagro-eng-note">Protected TAGRO hydraulic constants are used directly. Geometry and accepted elevation come from this same map object.</div></div>`;const save=()=>{g.size=+document.querySelector('#engSize').value;g.material=document.querySelector('#engMaterial').value;g.sdr=+document.querySelector('#engSdr').value||13.6;window.TAGRO_SESSION?.schedule?.();render()};['#engSize','#engMaterial','#engSdr'].forEach(s=>document.querySelector(s)?.addEventListener('change',save))}
b.addEventListener('click',()=>{active=true;document.querySelectorAll('.tagro-cad-tab').forEach(x=>x.classList.toggle('on',x===b));document.querySelectorAll('.tagro-cad-pane').forEach(x=>x.classList.toggle('on',x===pane));render()});tabs.querySelectorAll('[data-cad-tab]:not([data-cad-tab="engineering"])').forEach(x=>x.addEventListener('click',()=>{active=false;pane.classList.remove('on')}));window.addEventListener('tagro:cadselect',render);window.addEventListener('tagro:cadchange',render);window.addEventListener('tagro:identitychange',render);document.addEventListener('change',e=>{if(e.target.closest?.('#cadMeasure'))setTimeout(render,0)});window.TAGRO_ENGINEERING_UI={render};}
boot();
})();