(()=>{
'use strict';
if(typeof map==='undefined'||!window.TAGRO_CAD||!window.TAGRO_MEASURE||!window.TAGROScience)return;
const q=s=>document.querySelector(s),SCI=window.TAGROScience,pipeRoles=['main','submain','lateral'];
const tabs=q('.tagro-cad-tabs'),measurePane=q('#cadMeasure');if(!tabs||!measurePane)return;
tabs.classList.add('tagro-has-design');
const tab=document.createElement('button');tab.className='tagro-cad-tab';tab.dataset.engineTab='design';tab.textContent='Design';tabs.appendChild(tab);
const pane=document.createElement('div');pane.id='cadDesign';pane.className='tagro-cad-pane';measurePane.insertAdjacentElement('afterend',pane);
let selected=window.TAGRO_CAD.getSelected?.()||null;const events=[];
function objectId(l){return l.options.tagroObjectId||(l.options.tagroObjectId='obj-eng-'+Date.now()+'-'+Math.random().toString(36).slice(2,7))}
function role(l){return l?.options?.tagroIdentityId||null}
function isPipe(l){return !!l&&pipeRoles.includes(role(l))&&window.TAGRO_MEASURE.measure(l)?.kind==='line'}
function defaults(r){if(r==='lateral')return{material:'LLDPE',mm:16,pressureClass:'',parentId:null,lengthOverride:null,manualFlowLph:null,emitterLph:null,emitterSpacingM:null,emitterCount:null};if(r==='submain')return{material:'PVC',mm:40,pressureClass:'4 kg',parentId:null,lengthOverride:null,manualFlowLph:null};return{material:'PVC',mm:50,pressureClass:'4 kg',parentId:null,lengthOverride:null,manualFlowLph:null}}
function eng(l){const r=role(l);if(!l.options.tagroEngineering||l.options.tagroEngineering.role!==r)l.options.tagroEngineering={version:'0.1',role:r,status:'proposed',provenance:{length:'map-measured',inputs:'designer',calculation:'TAGROScience 1.0.0'},...defaults(r),...(l.options.tagroEngineering||{}),role:r};return l.options.tagroEngineering}
function pipes(){return(window.TAGRO_CAD.getLayers?.()||[]).filter(isPipe)}
function find(id){return pipes().find(l=>objectId(l)===id)||null}
function mapLength(l){const m=window.TAGRO_MEASURE.measure(l);return m&&m.kind==='line'?m.length:null}
function designLength(l){const e=eng(l),m=mapLength(l);return Number.isFinite(+e.lengthOverride)&&+e.lengthOverride>0?+e.lengthOverride:m}
function elev(l){const x=l.options.tagroElevation||{},mapv=Array.isArray(x.map)?x.map:[],surv=Array.isArray(x.survey)?x.survey:[];if(x.accepted==='survey'&&Number.isFinite(surv[0])&&Number.isFinite(surv[1]))return{source:'Surveyed',start:+surv[0],end:+surv[1]};if(Number.isFinite(mapv[0])&&Number.isFinite(mapv[1]))return{source:'Map terrain',start:+mapv[0],end:+mapv[1]};return null}
function compatibleParents(l){const r=role(l);return pipes().filter(p=>p!==l&&((r==='lateral'&&['submain','main'].includes(role(p)))||(r==='submain'&&role(p)==='main')))}
function children(l){const id=objectId(l);return pipes().filter(p=>eng(p).parentId===id)}
function lateralFlow(l){const e=eng(l),len=designLength(l),d=+e.emitterLph,explicit=+e.emitterCount,spacing=+e.emitterSpacingM;if(!(d>0))return{flow:null,count:null,source:'missing emitter discharge'};let count=null,source='';if(explicit>0){count=explicit;source='entered emitter count'}else if(spacing>0&&len>0){count=Math.floor(len/spacing)+1;source='measured length + emitter spacing'}if(!(count>0))return{flow:null,count:null,source:'missing emitter count/spacing'};return{flow:d*count,count,source}}
function flowOf(l,seen=new Set()){const id=objectId(l);if(seen.has(id))return{flow:null,source:'relationship cycle'};seen.add(id);const e=eng(l);if(role(l)==='lateral')return lateralFlow(l);const cs=children(l);if(cs.length){let total=0,missing=0;cs.forEach(c=>{const f=flowOf(c,new Set(seen));if(f.flow>0)total+=f.flow;else missing++});if(total>0)return{flow:total,source:`${cs.length} connected child${cs.length===1?'':'ren'}`,missingChildren:missing}}const mf=+e.manualFlowLph;if(mf>0)return{flow:mf,source:'manual design flow'};return{flow:null,source:cs.length?'connected demand incomplete':'no connected demand/manual flow'}}
function hydraulic(l){const e=eng(l),len=designLength(l),f=flowOf(l),el=elev(l);if(!(len>0))return{ready:false,missing:'Measured/design length'};if(!(f.flow>0))return{ready:false,missing:f.source||'Flow'};if(!(e.mm>0))return{ready:false,missing:'Pipe size'};const fall=el?el.start-el.end:0,a=SCI.assess({role:role(l),lengthM:len,flowLph:f.flow,mm:+e.mm,fallM:fall,system:'standard'});if(!a.valid)return{ready:false,missing:'Hydraulic inputs'};const staticRise=el?el.end-el.start:null,velocity=SCI.velocity(f.flow,+e.mm),friction=a.headlossM,total=Number.isFinite(staticRise)&&Number.isFinite(friction)?friction+staticRise:null;return{ready:true,a,flow:f,el,fall,staticRise,velocity,friction,total,frictionBar:Number.isFinite(friction)?friction*0.0980665:null,totalBar:Number.isFinite(total)?total*0.0980665:null,maturity:el?'PRELIMINARY':'INDICATION'}}
function fmt(v,d=2){return Number.isFinite(v)?Number(v).toFixed(d):'—'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function label(l){const r=role(l);return r==='main'?'Main':r==='submain'?'Submain':r==='lateral'?'Lateral':'Unidentified'}
function emitChange(l,field,before,after){events.push({id:'eng-'+Date.now(),timestamp:new Date().toISOString(),source:'designer',objectId:objectId(l),field,before,after,ripple:'recalculate object and upstream connected demand'});window.dispatchEvent(new CustomEvent('tagro:engineeringchange',{detail:{layer:l,field,before,after}}))}
function set(l,key,value){const e=eng(l),before=e[key];e[key]=value;emitChange(l,key,before,value);render()}
function fieldRow(name,key,value,type='number',attrs=''){return`<div class="tagro-design-row"><label>${name}</label><input data-eng="${key}" type="${type}" value="${value??''}" ${attrs}></div>`}
function selectRow(name,key,value,options){return`<div class="tagro-design-row"><label>${name}</label><select data-eng="${key}">${options.map(o=>`<option value="${esc(o.value)}" ${String(o.value)===String(value)?'selected':''}>${esc(o.label)}</option>`).join('')}</select></div>`}
function render(){if(!pane.classList.contains('on'))return;selected=window.TAGRO_CAD.getSelected?.()||selected;if(!selected){pane.innerHTML='<div class="tagro-design-empty">Select an identified Main, Submain or Lateral. Design reuses that object’s measured geometry; it does not create another pipe.</div>';return}if(!isPipe(selected)){pane.innerHTML=`<div class="tagro-design-empty"><b>${esc(label(selected))}</b> is not a hydraulic pipe role. Identify a line as Main, Submain or Lateral first.</div>`;return}const l=selected,e=eng(l),r=role(l),ml=mapLength(l),dl=designLength(l),el=elev(l),f=flowOf(l),h=hydraulic(l),parents=compatibleParents(l),cs=children(l),sizes=SCI.DEFAULT_SIZES[r]||[];
let demand='';if(r==='lateral')demand=`<div class="tagro-design-section"><h4>Lateral demand</h4>${fieldRow('Emitter discharge (LPH)','emitterLph',e.emitterLph,'number','min="0" step="0.1"')}${fieldRow('Emitter spacing (m)','emitterSpacingM',e.emitterSpacingM,'number','min="0" step="0.1"')}${fieldRow('Emitter count override','emitterCount',e.emitterCount,'number','min="0" step="1"')}<div class="tagro-design-note">If count is blank, count = measured/design length ÷ spacing + first outlet. Flow = emitter discharge × count.</div></div>`;else demand=`<div class="tagro-design-section"><h4>Demand</h4>${fieldRow('Manual flow if no children (LPH)','manualFlowLph',e.manualFlowLph,'number','min="0" step="1"')}${cs.length?`<div>${cs.map(c=>{const cf=flowOf(c);return`<div class="tagro-design-child"><span>${label(c)}</span><b>${cf.flow>0?fmt(cf.flow,0)+' LPH':'incomplete'}</b></div>`}).join('')}</div>`:''}<div class="tagro-design-note">Connected child demand is aggregated upstream automatically. Manual flow is used only when connected demand is absent.</div></div>`;
const parent=r==='main'?'':selectRow('Fed by / parent','parentId',e.parentId,[{value:'',label:'Not connected'},...parents.map(p=>({value:objectId(p),label:`${label(p)} · ${fmt(designLength(p),1)} m`}))]);
const result=h.ready?`<div class="tagro-design-section"><h4>Hydraulic check</h4><div class="tagro-design-grid"><div class="tagro-design-card"><span>Design flow</span><b>${fmt(h.flow.flow,0)} LPH</b></div><div class="tagro-design-card"><span>Velocity</span><b>${fmt(h.velocity,2)} m/s</b></div><div class="tagro-design-card"><span>Friction head loss</span><b>${fmt(h.friction,2)} m</b></div><div class="tagro-design-card"><span>Pressure loss · friction</span><b>${fmt(h.frictionBar,3)} bar</b></div><div class="tagro-design-card"><span>Static rise/fall</span><b>${h.el?`${h.staticRise>=0?'Rise':'Fall'} ${fmt(Math.abs(h.staticRise),1)} m`:'Not loaded'}</b></div><div class="tagro-design-card"><span>Net line head</span><b>${h.total===null?'—':fmt(h.total,2)+' m'}</b></div><div class="tagro-design-card"><span>Permissible length</span><b>${fmt(h.a.permissibleM,1)} m</b></div><div class="tagro-design-card"><span>Flow regime</span><b>${esc(h.a.regime)}</b></div></div><div class="${h.a.passes?'tagro-design-ok':'tagro-design-fail'}">${h.maturity} · protected TAGRO hydraulic check: <b>${h.a.passes?'within permissible length':'outside permissible length'}</b>${h.el?' using '+h.el.source:' · elevation not yet included'}.</div><div class="tagro-design-source">Calculation: TAGROScience ${SCI.version} · length: ${Number.isFinite(+e.lengthOverride)&&+e.lengthOverride>0?'manual override; map retained':'map measured'} · flow: ${esc(h.flow.source)}.</div></div>`:`<div class="tagro-design-warn">Hydraulic result not issued yet: ${esc(h.missing)} is missing. Existing measurements and inputs are retained.</div>`;
pane.innerHTML=`<div class="tagro-design"><div class="tagro-design-head"><div class="tagro-design-role">${label(l)}</div><span class="tagro-design-badge">${h.ready?h.maturity:'WORKING'}</span></div><div class="tagro-design-grid"><div class="tagro-design-card"><span>Map measured length</span><b>${fmt(ml,2)} m</b></div><div class="tagro-design-card"><span>Design length</span><b>${fmt(dl,2)} m</b></div><div class="tagro-design-card"><span>Accepted elevation</span><b>${el?`${fmt(el.start,1)} → ${fmt(el.end,1)} m`:'Not loaded'}</b></div><div class="tagro-design-card"><span>Demand</span><b>${f.flow>0?fmt(f.flow,0)+' LPH':'Incomplete'}</b></div></div><div class="tagro-design-section"><h4>Pipe</h4>${fieldRow('Length override (m)','lengthOverride',e.lengthOverride,'number','min="0" step="0.1"')}${selectRow('Nominal size (mm)','mm',e.mm,sizes.map(x=>({value:x,label:x+' mm'})))}${selectRow('Material','material',e.material,(r==='lateral'?['LLDPE']:['PVC','HDPE','Oval Hose']).map(x=>({value:x,label:x})))}${fieldRow('Pressure class','pressureClass',e.pressureClass,'text')}${parent}<div class="tagro-design-note">Map length remains the measured fact. A length override is a separate proposed design input.</div></div>${demand}${result}</div>`;
pane.querySelectorAll('[data-eng]').forEach(el=>{const key=el.dataset.eng;el.onchange=()=>{let v=el.value;if(el.type==='number')v=v===''?null:Number(v);if(key==='parentId'&&v==='')v=null;set(l,key,v)}});e.calculation=h.ready?{version:SCI.version,timestamp:new Date().toISOString(),maturity:h.maturity,lengthM:dl,lengthSource:Number.isFinite(+e.lengthOverride)&&+e.lengthOverride>0?'manual-override':'map-measured',flowLph:h.flow.flow,flowSource:h.flow.source,elevationSource:h.el?.source||null,headlossM:h.friction,staticRiseM:h.staticRise,netHeadM:h.total,velocityMps:h.velocity,permissibleM:h.a.permissibleM,passes:h.a.passes}:null}
function openDesign(){window.TAGRO_DRAW_UX?.exitMapModes?.();tabs.querySelectorAll('.tagro-cad-tab').forEach(x=>x.classList.remove('on'));q('.tagro-cad')?.querySelectorAll('.tagro-cad-pane').forEach(x=>x.classList.remove('on'));tab.classList.add('on');pane.classList.add('on');render()}
tab.onclick=e=>{e.preventDefault();e.stopPropagation();openDesign()};
tabs.querySelectorAll('[data-cad-tab]').forEach(b=>b.addEventListener('click',()=>{tab.classList.remove('on');pane.classList.remove('on')}));
window.addEventListener('tagro:cadselect',e=>{selected=e.detail?.layer||null;if(pane.classList.contains('on'))render()});
window.addEventListener('tagro:identitychange',()=>{if(pane.classList.contains('on'))render()});
window.addEventListener('tagro:cadchange',()=>{if(pane.classList.contains('on'))render()});
window.addEventListener('tagro:engineeringchange',()=>{if(pane.classList.contains('on'))render()});
window.TAGRO_IRRIGATION_ENGINE={version:'0.1.0',flowOf,hydraulic,children,compatibleParents,events,render,openDesign};
})();