(()=>{
if(typeof map==='undefined')return;
const G=9.80665,NU=8.93e-7;
const defaults={sourceHeadM:20,minEmitterHeadM:7,targetUniformityPct:90,maxVelocityMps:2,connectionToleranceM:12,roughnessMm:.0015,emitter:{dischargeLph:8,spacingM:10,nominalHeadM:10,pressureExponent:.5}};
let settings={...defaults,...JSON.parse(localStorage.getItem('tagro.network.settings.v1')||'{}')};
const role=l=>l?.options?.tagroIdentityId||null;
const measurable=l=>window.TAGRO_MEASURE?.measure?.(l)||null;
const ensureId=l=>l.options.tagroObjectId||(l.options.tagroObjectId=crypto.randomUUID());
function llRing(v){if(!Array.isArray(v))return[];if(v.length&&v[0]&&typeof v[0].lat==='number')return v;for(const x of v){const r=llRing(x);if(r.length)return r}return[]}
function endpoints(l){const p=l?.getLatLngs?llRing(l.getLatLngs()):[];return p.length?[p[0],p[p.length-1]]:[]}
function pointSegM(p,a,b){const z=map.getZoom(),P=map.project(p,z),A=map.project(a,z),B=map.project(b,z),vx=B.x-A.x,vy=B.y-A.y,wx=P.x-A.x,wy=P.y-A.y,c1=vx*wx+vy*wy,c2=vx*vx+vy*vy;let t=c2?Math.max(0,Math.min(1,c1/c2)):0;const Q=L.point(A.x+t*vx,A.y+t*vy),q=map.unproject(Q,z);return{distanceM:map.distance(p,q),latlng:q,t}}
function nearestOnLine(p,l){const a=llRing(l.getLatLngs?.()||[]);let best={distanceM:Infinity,latlng:null,t:0,segment:0,alongM:0},cum=0,total=0;for(let i=1;i<a.length;i++)total+=map.distance(a[i-1],a[i]);for(let i=1;i<a.length;i++){const seg=map.distance(a[i-1],a[i]),x=pointSegM(p,a[i-1],a[i]);if(x.distanceM<best.distanceM)best={...x,segment:i-1,alongM:cum+seg*x.t,totalM:total};cum+=seg}return best}
function candidateParent(child,parents){const ep=endpoints(child);let best=null;for(const p of parents){for(let ei=0;ei<ep.length;ei++){const n=nearestOnLine(ep[ei],p);if(!best||n.distanceM<best.distanceM)best={parent:p,childEndpoint:ei,...n}}}return best}
function buildRelationships(){const ls=(window.TAGRO_CAD?.getLayers?.()||[]).filter(l=>map.hasLayer(l)),mains=ls.filter(l=>role(l)==='main'),subs=ls.filter(l=>role(l)==='submain'),lats=ls.filter(l=>role(l)==='lateral'),edges=[];for(const l of lats){const c=candidateParent(l,subs.length?subs:mains);if(c&&c.distanceM<=settings.connectionToleranceM)edges.push({id:ensureId(l)+'>'+ensureId(c.parent),child:l,parent:c.parent,kind:role(c.parent)==='submain'?'lateral-submain':'lateral-main',status:'inferred',distanceM:c.distanceM,parentAlongM:c.alongM,join:c.latlng})}for(const s of subs){const c=candidateParent(s,mains);if(c&&c.distanceM<=settings.connectionToleranceM)edges.push({id:ensureId(s)+'>'+ensureId(c.parent),child:s,parent:c.parent,kind:'submain-main',status:'inferred',distanceM:c.distanceM,parentAlongM:c.alongM,join:c.latlng})}return{layers:ls,mains,subs,laterals:lats,edges,orphans:[...lats,...subs].filter(l=>!edges.some(e=>e.child===l))}}
function acceptedElevation(l){const z=l?.options?.tagroElevation||{},s=Array.isArray(z.survey)?z.survey:[],m=Array.isArray(z.map)?z.map:[];if(z.accepted==='survey'&&Number.isFinite(s[0])&&Number.isFinite(s[1]))return[s[0],s[1]];if(Number.isFinite(m[0])&&Number.isFinite(m[1]))return[m[0],m[1]];return null}
function eng(l){const r=role(l),d=r==='lateral'?{size:16,material:'LLDPE',sdr:13.6}:{size:r==='submain'?40:50,material:'PVC',sdr:13.6};return l.options.tagroEngineering||(l.options.tagroEngineering=d)}
function idM(mm){return (window.TAGRO_HYDRAULICS?.constants?.ID_MM?.[+mm]||(+mm*.9))/1000}
function frictionFactor(Re,rel){if(!(Re>0))return 0;if(Re<2300)return 64/Re;return .25/Math.pow(Math.log10(rel/3.7+5.74/Math.pow(Re,.9)),2)}
function headLoss(flowLps,lengthM,mm,roughnessMm=settings.roughnessMm){const D=idM(mm),Q=flowLps/1000,A=Math.PI*D*D/4,v=A?Q/A:0,Re=v*D/NU,f=frictionFactor(Re,(roughnessMm/1000)/D),hf=f*(lengthM/D)*(v*v/(2*G));return{hf,v,Re,f}}
function emitterConfig(l){return l.options.tagroEmitter||(l.options.tagroEmitter={...settings.emitter})}
function emitterCount(length,cfg){return Math.max(1,Math.floor(length/Math.max(.1,cfg.spacingM))+1)}
function emitterQ(cfg,head){if(!(head>0))return 0;return cfg.dischargeLph*Math.pow(Math.max(0,head)/Math.max(.1,cfg.nominalHeadM),cfg.pressureExponent)}
function solveLateral(l,inletHeadM){const m=measurable(l),len=m?.length||0,cfg=emitterConfig(l),g=eng(l),n=emitterCount(len,cfg),seg=n>1?len/(n-1):len,z=acceptedElevation(l),dz=z?z[1]-z[0]:0;let qs=Array(n).fill(cfg.dischargeLph),heads=Array(n).fill(inletHeadM);for(let it=0;it<40;it++){let h=inletHeadM,maxDelta=0;for(let i=0;i<n;i++){heads[i]=h;const nq=emitterQ(cfg,h);maxDelta=Math.max(maxDelta,Math.abs(nq-qs[i]));qs[i]=.55*qs[i]+.45*nq;if(i<n-1){const remaining=qs.slice(i+1).reduce((a,b)=>a+b,0)/3600;const loss=headLoss(remaining,seg,g.size).hf;h-=loss+dz/(n-1)}}if(maxDelta<.002)break}const totalLph=qs.reduce((a,b)=>a+b,0),avg=totalLph/n,min=Math.min(...qs),max=Math.max(...qs),uniformity=max>0?100*min/max:0,pressureMin=Math.min(...heads),pressureMax=Math.max(...heads),flowLps=totalLph/3600,hl=headLoss(flowLps,len,g.size);return{layer:l,id:ensureId(l),role:'lateral',lengthM:len,sizeMm:+g.size,emitters:n,totalLph,flowLps,avgEmitterLph:avg,minEmitterLph:min,maxEmitterLph:max,uniformityPct:uniformity,inletHeadM,pressureMinM:pressureMin,pressureMaxM:pressureMax,velocityMps:hl.v,emitter:cfg}}
function pipeLoss(l,flowLps){const m=measurable(l),g=eng(l),len=m?.length||0,z=acceptedElevation(l),dz=z?z[1]-z[0]:0,h=headLoss(flowLps,len,g.size);return{layer:l,id:ensureId(l),role:role(l),lengthM:len,sizeMm:+g.size,flowLps,frictionLossM:h.hf,elevationChangeM:dz,totalHeadChangeM:h.hf+dz,velocityMps:h.v}}
function evaluate(){const net=buildRelationships(),rootHead=settings.sourceHeadM,results=new Map(),children=new Map();for(const e of net.edges){if(!children.has(e.parent))children.set(e.parent,[]);children.get(e.parent).push(e.child)}
function demand(l,inletHead){const r=role(l);if(r==='lateral'){const x=solveLateral(l,inletHead);results.set(l,x);return x.flowLps}const kids=children.get(l)||[];let total=0;for(const k of kids)total+=demand(k,inletHead);const p=pipeLoss(l,total);const outHead=inletHead-p.totalHeadChangeM;p.inletHeadM=inletHead;p.outletHeadM=outHead;results.set(l,p);if(kids.length){results.delete(l);let total2=0;for(const k of kids)total2+=demand(k,outHead);const p2=pipeLoss(l,total2);p2.inletHeadM=inletHead;p2.outletHeadM=inletHead-p2.totalHeadChangeM;results.set(l,p2);return total2}return total}
for(const main of net.mains)demand(main,rootHead);for(const l of net.laterals)if(!results.has(l))results.set(l,solveLateral(l,rootHead));const lateralResults=[...results.values()].filter(x=>x.role==='lateral'),pipeResults=[...results.values()].filter(x=>x.role!=='lateral');const totalDemandLps=net.mains.reduce((s,m)=>s+(results.get(m)?.flowLps||0),0)||lateralResults.reduce((s,x)=>s+x.flowLps,0),minUniformity=lateralResults.length?Math.min(...lateralResults.map(x=>x.uniformityPct)):0,maxVelocity=[...results.values()].length?Math.max(...[...results.values()].map(x=>x.velocityMps||0)):0,minPressure=lateralResults.length?Math.min(...lateralResults.map(x=>x.pressureMinM)):0;const flags=[];if(net.orphans.length)flags.push(`${net.orphans.length} unconnected pipe${net.orphans.length===1?'':'s'}`);if(lateralResults.some(x=>x.uniformityPct<settings.targetUniformityPct))flags.push('emitter uniformity below target');if(lateralResults.some(x=>x.pressureMinM<settings.minEmitterHeadM))flags.push('emitter pressure below target');if(maxVelocity>settings.maxVelocityMps)flags.push('pipe velocity above target');return{net,results,lateralResults,pipeResults,totalDemandLps,minUniformity,maxVelocity,minPressure,flags,efficient:!flags.length}}
function setSettings(p){settings={...settings,...p,emitter:{...settings.emitter,...(p.emitter||{})}};localStorage.setItem('tagro.network.settings.v1',JSON.stringify(settings));window.TAGRO_SESSION?.schedule?.();window.dispatchEvent(new CustomEvent('tagro:networkchange'))}
window.TAGRO_NETWORK={buildRelationships,evaluate,solveLateral,headLoss,emitterQ,getSettings:()=>JSON.parse(JSON.stringify(settings)),setSettings};
})();