(()=>{
if(typeof map==='undefined')return;
const VERSION=1,API=(window.TAGRO_API_BASE||localStorage.getItem('tagro.api.base')||'').replace(/\/$/,'');
let restoring=false,saveTimer=null,user={id:'trial',name:'Trial User',trial:true},plotId='trial-current';
const q=s=>document.querySelector(s);
function clone(v){try{return JSON.parse(JSON.stringify(v))}catch(e){return null}}
function flatten(v){if(!Array.isArray(v))return v;if(v.length&&v[0]&&typeof v[0].lat==='number')return v.map(x=>[x.lat,x.lng]);return v.map(flatten)}
function shape(l){return l.options?.tagroShape||(l.pm?.getShape?.()||'')}
function record(l){if(!l||l.options?.pmIgnore)return null;const s=shape(l),base={id:l.options.tagroObjectId||crypto.randomUUID(),shape:s,identity:l.options.tagroIdentityId||null,note:l.options.tagroNote||'',style:{color:l.options.color,weight:l.options.weight,fillColor:l.options.fillColor,fillOpacity:l.options.fillOpacity},elevation:clone(l.options.tagroElevation||null),engineering:clone(l.options.tagroEngineering||null)};l.options.tagroObjectId=base.id;if(l instanceof L.Circle)return{...base,type:'circle',latlng:[l.getLatLng().lat,l.getLatLng().lng],radius:l.getRadius()};if(l instanceof L.CircleMarker)return{...base,type:'circlemarker',latlng:[l.getLatLng().lat,l.getLatLng().lng],radius:l.getRadius()};if(l instanceof L.Marker)return{...base,type:s==='Text'?'text':'marker',latlng:[l.getLatLng().lat,l.getLatLng().lng],text:l.options.text||l.options._text||l._text||''};if(l.getLatLngs)return{...base,type:(s==='Polygon'||s==='Rectangle')?'polygon':'line',latlngs:flatten(l.getLatLngs())};return null}
function snapshot(){const layers=(window.TAGRO_CAD?.getLayers?.()||map.pm?.getGeomanDrawLayers?.()||[]).map(record).filter(Boolean);return{version:VERSION,plotId,userId:user.id,view:{center:[map.getCenter().lat,map.getCenter().lng],zoom:map.getZoom()},layers,updatedAt:new Date().toISOString()}}
function localKey(){return`tagro.plot.${user.id}.${plotId}.v${VERSION}`}
function status(t){const el=q('#tagroSaveState');if(el)el.textContent=t}
async function remoteSave(data){if(!API||user.trial)return false;const r=await fetch(API+'/api/plots/'+encodeURIComponent(plotId),{method:'PUT',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw new Error('remote save failed');return true}
async function saveNow(){if(restoring)return;const data=snapshot();try{localStorage.setItem(localKey(),JSON.stringify(data));status('Saved');if(API&&!user.trial){status('Syncing…');await remoteSave(data);status('Saved online')}}catch(e){status('Saved locally')}}
function schedule(){if(restoring)return;status('Saving…');clearTimeout(saveTimer);saveTimer=setTimeout(saveNow,550)}
function latlng(v){return L.latLng(v[0],v[1])}
function nested(v){return Array.isArray(v)&&v.length===2&&typeof v[0]==='number'?latlng(v):v.map(nested)}
function addRec(r){let l;if(r.type==='circle')l=L.circle(latlng(r.latlng),{radius:r.radius,...r.style});else if(r.type==='circlemarker')l=L.circleMarker(latlng(r.latlng),{radius:r.radius,...r.style});else if(r.type==='marker')l=L.marker(latlng(r.latlng));else if(r.type==='text'){l=L.marker(latlng(r.latlng),{icon:L.divIcon({className:'tagro-restored-text',html:`<span>${String(r.text||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</span>`})});l.options.text=r.text||''}else if(r.type==='polygon')l=L.polygon(nested(r.latlngs),r.style||{});else l=L.polyline(nested(r.latlngs),r.style||{});l.options.tagroShape=r.shape;l.options.tagroObjectId=r.id;l.options.tagroIdentityId=r.identity;l.options.tagroNote=r.note||'';l.options.tagroElevation=r.elevation||undefined;l.options.tagroEngineering=r.engineering||undefined;l.addTo(map);try{map.fire('pm:create',{layer:l,shape:r.shape||l.pm?.getShape?.()})}catch(e){}return l}
async function loadData(){let data=null;if(API&&!user.trial){try{const r=await fetch(API+'/api/plots/'+encodeURIComponent(plotId),{credentials:'include'});if(r.ok)data=await r.json()}catch(e){}}if(!data){try{data=JSON.parse(localStorage.getItem(localKey())||'null')}catch(e){}}if(!data)return;restoring=true;try{for(const l of (window.TAGRO_CAD?.getLayers?.()||[]).slice())if(map.hasLayer(l))map.removeLayer(l);(data.layers||[]).forEach(addRec);if(data.view?.center)map.setView(data.view.center,data.view.zoom||17)}finally{restoring=false;status(user.trial?'Trial saved':'Loaded') }}
function ui(){const controls=q('.controls');if(!controls)return;const state=document.createElement('span');state.id='tagroSaveState';state.className='tagro-save-state';state.textContent='Trial saved';const b=document.createElement('button');b.id='tagroAccount';b.className='tagro-account-badge trial';b.textContent='Trial User';b.onclick=openAccount;controls.prepend(state);controls.prepend(b);const d=document.createElement('dialog');d.id='tagroAccountDialog';d.innerHTML=`<form method="dialog" class="tagro-account-dialog"><div class="tagro-account-head"><b>TAGRO account</b><button value="cancel">×</button></div><div id="tagroAccountCurrent"></div><input id="tagroEmail" type="email" placeholder="Email"><input id="tagroPassword" type="password" placeholder="Password"><div class="tagro-account-actions"><button type="button" id="tagroLogin">Sign in</button><button type="button" id="tagroRegister">Create account</button></div><div id="tagroAccountMsg" class="tagro-account-msg"></div></form>`;document.body.appendChild(d);q('#tagroLogin').onclick=()=>auth('login');q('#tagroRegister').onclick=()=>auth('register')}
function renderUser(){const b=q('#tagroAccount');if(b){b.textContent=user.name||user.email||'User';b.classList.toggle('trial',!!user.trial)}q('#tagroAccountCurrent')&&(q('#tagroAccountCurrent').textContent=user.trial?'Current workspace: Trial User':`Signed in: ${user.email||user.name}`)}
function openAccount(){renderUser();q('#tagroAccountDialog').showModal()}
async function auth(kind){const msg=q('#tagroAccountMsg');if(!API){msg.textContent='Account server is not deployed yet. Trial work is still saved on this device.';return}const email=q('#tagroEmail').value.trim(),password=q('#tagroPassword').value;if(!email||!password)return;msg.textContent='Working…';try{const r=await fetch(API+'/api/auth/'+kind,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Sign in failed');user={...d.user,trial:false};plotId=d.plotId||'current';renderUser();await loadData();schedule();msg.textContent='Connected'}catch(e){msg.textContent=e.message}}
async function session(){if(!API)return;try{const r=await fetch(API+'/api/session',{credentials:'include'});if(r.ok){const d=await r.json();if(d.user){user={...d.user,trial:false};plotId=d.plotId||'current';renderUser();await loadData()}}}catch(e){}}
ui();renderUser();['pm:create','pm:edit','pm:dragend','pm:remove'].forEach(ev=>map.on(ev,schedule));window.addEventListener('tagro:identitychange',schedule);window.addEventListener('tagro:cadchange',schedule);document.addEventListener('change',e=>{if(e.target.closest?.('.tagro-cad'))schedule()});window.addEventListener('beforeunload',()=>{try{localStorage.setItem(localKey(),JSON.stringify(snapshot()))}catch(e){}});loadData().then(session);
window.TAGRO_SESSION={snapshot,saveNow,schedule,getUser:()=>user,getPlotId:()=>plotId,apiBase:API};
})();