export const TASKS={
 newNetwork:{label:'Irrigate a field',outcome:'PRELIMINARY',facts:['purpose.primary','field.cropPrimary','field.roughGeometry','water.exists','application.intent'],optional:['water.location','pump.power','field.cropSupporting','field.access','field.elevation'],routes:['purpose','farm','field','water','application','network','review']},
 improveExisting:{label:'Improve what I have',outcome:'PROPOSED',facts:['purpose.primary','existing.problem','existing.whatExists','field.affectedArea'],optional:['pump.power','application.intent','field.elevation'],routes:['purpose','farm','field','water','network','review']},
 pumpCheck:{label:'Check my pump',outcome:'PRELIMINARY',facts:['pump.power','demand.activeEstimate','route.lengthEstimate'],optional:['pump.head','field.elevation','main.diameter'],routes:['purpose','water','network','review']},
 chooseApplication:{label:'Choose an emitter / sprinkler',outcome:'PROPOSED',facts:['field.cropPrimary','field.cropRole','water.constraint','purpose.primary'],optional:['field.plantSpacing','soil.context','pump.pressure'],routes:['purpose','farm','water','application','review']},
 waterSaving:{label:'Use less water',outcome:'PRELIMINARY',facts:['purpose.primary','field.cropPrimary','water.constraint','application.current'],optional:['soil.context','field.priority','runtime.current'],routes:['purpose','farm','water','application','review']},
 materialEstimate:{label:'Estimate materials',outcome:'PRELIMINARY',facts:['network.hasObjects'],optional:['network.accepted','catalogue.context'],routes:['purpose','field','network','review']}
};
export const PURPOSES=[['surviveSummer','Keep crops alive through dry periods'],['yield','Improve yield / crop performance'],['labour','Reduce daily labour'],['water','Use less water'],['income','Improve farm income'],['expand','Build something easy to expand'],['cost','Keep initial cost low'],['reliability','Make irrigation more reliable']];
export const CROP_ROLES=[['sole','Main / sole crop'],['primary','Primary crop with others'],['supporting','Supporting intercrop'],['temporary','Temporary intercrop'],['incidental','Incidental / not design-driving']];
export const CROP_PURPOSES=[['income','Income'],['food','Food for home'],['weed','Weed / ground suppression'],['culture','Cultural / customary practice'],['establishment','Income while another crop establishes'],['soil','Soil / shade / farm function'],['other','Another reason']];
export function requiredFor(taskId){return TASKS[taskId]?.facts||[];}
export function completion(taskId,factMap){const req=requiredFor(taskId);if(!req.length)return 1;return req.filter(k=>factMap[k]!=null&&factMap[k]!==''&&factMap[k]!==false).length/req.length;}
export function reflection(f){const crop=f['field.cropPrimary'];const second=f['field.cropSupporting'];const role=f['field.cropRole'];const purposes=f['field.cropPurposes']||[];const mainPurpose=f['purpose.primary'];let lines=[];if(mainPurpose)lines.push(`Your main reason is ${mainPurpose.toLowerCase()}.`);if(crop&&second){let r=role==='supporting'||role==='temporary'?`${second} appears to support ${crop}, rather than drive the permanent system.`:`${crop} and ${second} both matter to this field.`;lines.push(r);}if(purposes.length)lines.push(`The supporting crop matters for ${purposes.join(', ').toLowerCase()}.`);return lines.join(' ' )||'TAGRO will reflect the working purpose here as you answer.';}
export function demand(f){const q=Number(f['application.discharge']||0),n=Number(f['application.countPerPlant']||0),plants=Number(f['field.plantCount']||0);const plant=q*n;return{plant,total:plant*plants};}
const K={lateral:{12:141.9,16:236.8,20:358.2},submain:{40:986.4,50:1537.9,63:2312.5},main:{40:986.4,50:1537.9,63:2312.5}};const E=.6494;
export function permissible(role,diameter,spacing){const k=K[role]?.[Number(diameter)],s=Number(spacing);if(!k||!s)return null;return Math.round(k/Math.pow(s,E));}
export function maturity(taskId,factMap){const c=completion(taskId,factMap);if(c<1)return{label:'INDICATION',note:'Useful direction only; some consequential facts are still missing.'};return{label:TASKS[taskId]?.outcome||'PRELIMINARY',note:'Sub-minimum task evidence is present. Further detail is optional unless a hard engineering gate appears.'};}
