import {put,all,byProject,remove,id} from './db.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], now=()=>new Date().toISOString(), clone=v=>JSON.parse(JSON.stringify(v));
const PIPE=['main','submain','lateral'], COLOR={main:'#2e6fd0',submain:'#2f8a60',lateral:'#d47a2a',boundary:'#ffffff',source:'#43a8ff'};
let project,features=[],map,basemap='imagery',mode='select',draft=null,selectedId=null,undoStack=[],redoStack=[],markers=[],moveState=null,measurePts=[];

boot();
async function boot(){const ps=await all('projects');project=ps.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||'')))[0]||{id:id('project'),name:'New irrigation job',createdAt:now(),updatedAt:now(),status:'working'};await put('projects',project);features=await byProject('features',project.id);$('#projectName').textContent=project.name||'Irrigation job';bind();initMap();renderSummary();}
function bind(){
 $('#backBtn').onclick=()=>openSheet('exitSheet');$('#returnBtn').onclick=()=>location.href='./run.html#field';$('#layerBtn').onclick=()=>openSheet('layerSheet');
 $$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b.dataset.close));$$('[data-map]').forEach(b=>b.onclick=()=>setBasemap(b.dataset.map));
 $('#locateBtn').onclick=locate;$('#fitBtn').onclick=fitDesign;$('#addTool').onclick=()=>openSheet('addSheet');$('#selectTool').onclick=enterSelect;$('#measureTool').onclick=beginMeasure;
 $$('[data-add]').forEach(b=>b.onclick=()=>requestCreate(b.dataset.add));$('#cancelBtn').onclick=cancelAction;$('#placeBtn').onclick=placePoint;$('#finishBtn').onclick=finishAction;$('#undoTool').onclick=undo;$('#redoTool').onclick=redo;
 $('#editBtn').onclick=beginEdit;$('#moveBtn').onclick=beginMove;$('#deleteBtn').onclick=deleteSelected;
}
function initMap(){map=new maplibregl.Map({container:'map',style:styleFor('imagery'),center:[76.918,8.968],zoom:17,maxZoom:19,minZoom:4,pitchWithRotate:false,dragRotate:false,touchPitch:false,attributionControl:false});map.addControl(new maplibregl.AttributionControl({compact:true}),'bottom-right');map.touchZoomRotate.disableRotation();map.on('load',()=>{installLayers();restoreView();});map.on('move',()=>{if(mode==='create'||mode==='measure')refreshDraft();});map.on('moveend',saveView);}
function styleFor(kind){const src=kind==='imagery'?{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Esri, Maxar, Earthstar Geographics'}:{type:'raster',tiles:['https://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}'],tileSize:256,maxzoom:19,attribution:'Esri'};return{version:8,sources:{base:src},layers:[{id:'base',type:'raster',source:'base'}]};}
function installLayers(){if(map.getSource('design'))return;map.addSource('design',{type:'geojson',data:collection()});map.addLayer({id:'boundary-fill',type:'fill',source:'design',filter:['==',['get','type'],'boundary'],paint:{'fill-color':'#5d8fdc','fill-opacity':.15}});map.addLayer({id:'boundary-line',type:'line',source:'design',filter:['==',['get','type'],'boundary'],paint:{'line-color':'#fff','line-width':3}});for(const t of PIPE)map.addLayer({id:t,type:'line',source:'design',filter:['==',['get','type'],t],paint:{'line-color':COLOR[t],'line-width':t==='main'?6:t==='submain'?5:4}});map.addLayer({id:'source',type:'circle',source:'design',filter:['==',['get','type'],'source'],paint:{'circle-radius':8,'circle-color':COLOR.source,'circle-stroke-color':'#fff','circle-stroke-width':3}});map.addSource('draft',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'draft-line',type:'line',source:'draft',paint:{'line-color':'#fff','line-width':3,'line-dasharray':[2,2]}});map.addLayer({id:'draft-fill',type:'fill',source:'draft',paint:{'fill-color':'#fff','fill-opacity':.1}});['boundary-fill','boundary-line','main','submain','lateral','source'].forEach(l=>map.on('click',l,e=>{if(mode!=='select')return;e.originalEvent.__handled=true;selectFeature(e.features?.[0]?.properties?.id);}));map.on('click',e=>{if(mode==='select'&&!e.originalEvent.__handled)clearSelection();});refresh();}
function collection(){return{type:'FeatureCollection',features:features.map(f=>({type:'Feature',geometry:f.geometry,properties:{id:f.id,type:f.type,upstreamId:f.upstreamId||'',diameterMm:f.diameterMm||''}}))};}
function refresh(){map?.getSource('design')?.setData(collection());renderSummary();}
function renderSummary(){const mains=features.filter(f=>f.type==='main').length,subs=features.filter(f=>f.type==='submain').length,lats=features.filter(f=>f.type==='lateral').length,disc=features.filter(f=>PIPE.includes(f.type)&&!reachesSource(f.id)).length;$('#summary').innerHTML=`<b>Network</b>${mains} main · ${subs} submain · ${lats} lateral${disc?` · <span style="color:#a45b11">${disc} not source-connected</span>`:' · connected'}`;}
function setBasemap(kind){basemap=kind;const c=map.getCenter(),z=map.getZoom();map.setStyle(styleFor(kind));map.once('styledata',()=>{installLayers();map.jumpTo({center:c,zoom:z});refreshDraft();});$('#layerBtn').textContent=kind==='imagery'?'Imagery':'Map';closeSheet('layerSheet');}
function restoreView(){try{const v=JSON.parse(localStorage.getItem(`tagro-field-design-view-${project.id}`));if(v){map.jumpTo(v);return}}catch{}if(features.length)fitDesign();}
function saveView(){const c=map.getCenter();localStorage.setItem(`tagro-field-design-view-${project.id}`,JSON.stringify({center:[c.lng,c.lat],zoom:map.getZoom()}));}
function locate(){navigator.geolocation?.getCurrentPosition(p=>{map.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:18,duration:500});setStatus(`Location accuracy about ${Math.round(p.coords.accuracy)} m. Use imagery to align the field.`);},()=>setStatus('Location was not available. Pan to the field.'),{enableHighAccuracy:true,timeout:10000,maximumAge:30000});}
function fitDesign(){if(!features.length){setStatus('Nothing drawn yet. Locate or pan to the field.');return}const coords=[];features.forEach(f=>walk(f.geometry.coordinates,c=>coords.push(c)));const b=coords.reduce((bb,c)=>bb.extend(c),new maplibregl.LngLatBounds(coords[0],coords[0]));map.fitBounds(b,{padding:70,maxZoom:18.4,duration:450});}
function walk(v,fn){if(typeof v?.[0]==='number')fn(v);else v?.forEach(x=>walk(x,fn));}
function openSheet(id){$$('.sheet').forEach(s=>s.classList.add('hidden'));$('#'+id).classList.remove('hidden');}
function closeSheet(id){$('#'+id)?.classList.add('hidden');}
function setStatus(t){$('#status').textContent=t;}
function enterSelect(){cancelAction();mode='select';$('#selectTool').classList.add('active');setStatus('Tap a design object to inspect, move, edit or delete it.');}
function requestCreate(type){closeSheet('addSheet');clearSelection();if(type==='submain'&&!features.some(f=>f.type==='main')){setStatus('A Submain needs a Main. Add the Main first.');return}if(type==='lateral'&&!features.some(f=>f.type==='submain')){setStatus('A Lateral needs a Submain. Add the Submain first.');return}mode='create';draft={type,coords:[],upstreamId:null};showPlace(type);if(type==='source')setStatus('Move the map until the crosshair is on the water source, then Place.');else if(type==='boundary')setStatus('Move the map under the crosshair. Place each corner, then Finish.');else if(type==='main')setStatus('Place the Main start. If it begins at a source, move close to the source and it will snap.');else setStatus(`First connect this ${label(type)} to a ${type==='submain'?'Main':'Submain'}. Move the crosshair onto it and Place.`);refreshDraft();}
function showPlace(type){$('#normalDock').classList.add('hidden');$('#placeDock').classList.remove('hidden');$('#reticle').classList.remove('hidden');$('#actionTitle').textContent=label(type);$('#actionHint').textContent='Move map under crosshair';$('#placeBtn').classList.remove('hidden');$('#finishBtn').classList.add('hidden');}
function centerCoord(){const c=map.getCenter();return[c.lng,c.lat];}
function placePoint(){if(mode==='measure'){measurePts.push(centerCoord());refreshDraft();setStatus(measurePts.length<2?'Place another point.':`${measureLength().toFixed(1)} m measured. Add points or Cancel.`);return}if(mode!=='create'||!draft)return;let c=centerCoord();if(draft.type==='source'){snapshot('Add source');const f=makeFeature('source',{type:'Point',coordinates:c});features.push(f);persist(f);cancelAction();selectFeature(f.id);return}
 if(draft.coords.length===0&&draft.type==='submain'){const s=snapAllowed(c,['main']);if(!s){setStatus('Start must connect to a Main. Move the crosshair onto the Main and Place.');return}c=s.coord;draft.upstreamId=s.id;}
 else if(draft.coords.length===0&&draft.type==='lateral'){const s=snapAllowed(c,['submain']);if(!s){setStatus('Start must connect to a Submain. Move the crosshair onto the Submain and Place.');return}c=s.coord;draft.upstreamId=s.id;}
 else if(draft.coords.length===0&&draft.type==='main'){const s=snapAllowed(c,['source'],24);if(s){c=s.coord;draft.upstreamId=s.id;}}
 else if(PIPE.includes(draft.type)){const s=snapAllowed(c,['main','submain','lateral','source'],18);if(s)c=s.coord;}
 draft.coords.push(c);$('#finishBtn').classList.toggle('hidden',draft.type==='boundary'?draft.coords.length<3:draft.coords.length<2);refreshDraft();setStatus(`${draft.coords.length} point${draft.coords.length===1?'':'s'} placed. Move the map for the next point.`);}
function snapAllowed(coord,types,px=22){const p=map.project(coord);let best=null;for(const f of features.filter(x=>types.includes(x.type))){if(f.type==='source'){const q=map.project(f.geometry.coordinates),d=Math.hypot(p.x-q.x,p.y-q.y);if(d<px&&(!best||d<best.d))best={d,coord:f.geometry.coordinates,id:f.id,type:f.type};}else if(PIPE.includes(f.type)){try{const near=turf.nearestPointOnLine(turf.lineString(f.geometry.coordinates),turf.point(coord),{units:'meters'});const q=map.project(near.geometry.coordinates),d=Math.hypot(p.x-q.x,p.y-q.y);if(d<px&&(!best||d<best.d))best={d,coord:near.geometry.coordinates,id:f.id,type:f.type};}catch{}}}return best;}
function refreshDraft(){const src=map?.getSource('draft');if(!src)return;const feats=[];if(draft?.coords?.length){const preview=[...draft.coords,centerCoord()];if(draft.type==='boundary'&&preview.length>=3)feats.push({type:'Feature',geometry:{type:'Polygon',coordinates:[[...preview,preview[0]]]},properties:{}});else if(draft.type!=='source')feats.push({type:'Feature',geometry:{type:'LineString',coordinates:preview},properties:{}});}if(measurePts.length){const p=[...measurePts,centerCoord()];if(p.length>=2)feats.push({type:'Feature',geometry:{type:'LineString',coordinates:p},properties:{}});}src.setData({type:'FeatureCollection',features:feats});}
async function finishAction(){if(mode!=='create'||!draft)return;const min=draft.type==='boundary'?3:2;if(draft.coords.length<min){setStatus(`Place at least ${min} points first.`);return}const geom=draft.type==='boundary'?{type:'Polygon',coordinates:[[...draft.coords,draft.coords[0]]]}:{type:'LineString',coordinates:draft.coords};if(draft.type==='boundary'&&turf.kinks({type:'Feature',geometry:geom,properties:{}}).features.length){setStatus('Boundary crosses itself. Undo or move a corner before finishing.');return}if(PIPE.includes(draft.type)&&duplicatePipe(geom)){setStatus('This pipe substantially overlaps an existing pipe. Adjust it before finishing.');return}snapshot(`Add ${draft.type}`);const f=makeFeature(draft.type,geom);f.upstreamId=draft.upstreamId;f.diameterMm=draft.type==='main'?50:draft.type==='submain'?40:draft.type==='lateral'?16:null;features.push(f);await persist(f);cancelAction();selectFeature(f.id);}
function makeFeature(type,geometry){return{id:id('feature'),projectId:project.id,type,geometry,status:'proposed',createdAt:now(),updatedAt:now()};}
async function persist(f){f.updatedAt=now();await put('features',f);await put('events',{id:id('event'),projectId:project.id,type:'field.design.changed',at:now(),payload:{featureId:f.id,featureType:f.type}});refresh();}
function duplicatePipe(geom){const cand=turf.lineString(geom.coordinates),len=turf.length(cand,{units:'meters'});return features.filter(f=>PIPE.includes(f.type)).some(f=>{try{let sum=0;turf.lineOverlap(cand,turf.lineString(f.geometry.coordinates),{tolerance:.5}).features.forEach(x=>sum+=turf.length(x,{units:'meters'}));return len&&sum/len>.6}catch{return false}});}
function cancelAction(){mode='select';draft=null;measurePts=[];clearMarkers();$('#placeDock').classList.add('hidden');$('#normalDock').classList.remove('hidden');$('#reticle').classList.add('hidden');$('#selectTool').classList.add('active');map?.getSource('draft')?.setData({type:'FeatureCollection',features:[]});}
function beginMeasure(){clearSelection();mode='measure';measurePts=[];$('#normalDock').classList.add('hidden');$('#placeDock').classList.remove('hidden');$('#reticle').classList.remove('hidden');$('#actionTitle').textContent='Measure';$('#actionHint').textContent='Place two or more points';$('#placeBtn').classList.remove('hidden');$('#finishBtn').classList.add('hidden');setStatus('Move the map under the crosshair and place measurement points.');}
function measureLength(){let n=0;for(let i=1;i<measurePts.length;i++)n+=turf.distance(turf.point(measurePts[i-1]),turf.point(measurePts[i]),{units:'kilometers'})*1000;return n;}
function selectFeature(fid){selectedId=fid;const f=features.find(x=>x.id===fid);if(!f)return;openSheet('selectSheet');$('#selectedType').textContent=label(f.type);$('#selectedName').textContent=f.type==='boundary'?'Field boundary':label(f.type);const stats=[];if(f.type==='boundary'){stats.push(stat('Area',formatArea(turf.area(f))),stat('Perimeter',`${lineLength(turf.polygonToLine(f)).toFixed(1)} m`));}else if(PIPE.includes(f.type)){stats.push(stat('Length',`${lineLength(f).toFixed(1)} m`),stat('Size',`${f.diameterMm||'—'} mm`));}$('#selectedStats').innerHTML=stats.join('');const logic=$('#selectedLogic');if(PIPE.includes(f.type)){const ok=reachesSource(f.id);logic.className='logic'+(ok?'':' warn');logic.textContent=ok?'Connected through the network to a water source.':'Not yet connected through the network to a water source.';}else{logic.className='logic';logic.textContent=f.type==='source'?'Water source node for the irrigation network.':'This boundary defines field geometry; network objects remain independently editable.';}const d=$('#downstreamActions');d.innerHTML='';if(f.type==='main')d.innerHTML='<button data-child="submain">＋ Add Submain from this Main</button>';if(f.type==='submain')d.innerHTML='<button data-child="lateral">＋ Add Lateral from this Submain</button>';d.querySelectorAll('[data-child]').forEach(b=>b.onclick=()=>beginChild(f,b.dataset.child));}
function stat(a,b){return`<div class="stat"><small>${a}</small><b>${b}</b></div>`}function formatArea(m2){return m2>=4046.856?`${(m2/4046.856).toFixed(2)} ac`:`${Math.round(m2)} m²`;}function lineLength(f){return turf.length(f,{units:'kilometers'})*1000;}
function beginChild(parent,type){closeSheet('selectSheet');mode='create';draft={type,coords:[],upstreamId:parent.id,parentRequired:parent.id};showPlace(type);setStatus(`Connect the ${label(type)} to this ${label(parent.type)}. Move the crosshair onto it and Place.`);}
function reachesSource(fid,seen=new Set()){if(seen.has(fid))return false;seen.add(fid);const f=features.find(x=>x.id===fid);if(!f)return false;if(f.type==='source')return true;if(!f.upstreamId)return false;return reachesSource(f.upstreamId,seen);}
function clearSelection(){selectedId=null;closeSheet('selectSheet');clearMarkers();}
function beginEdit(){const f=features.find(x=>x.id===selectedId);if(!f)return;closeSheet('selectSheet');mode='edit';showEditMarkers(f);setStatus('Drag blue points to reshape. Tap a line midpoint to add a point. Changes save immediately.');}
function showEditMarkers(f){clearMarkers();const coords=f.type==='boundary'?f.geometry.coordinates[0].slice(0,-1):f.type==='source'?[f.geometry.coordinates]:f.geometry.coordinates;coords.forEach((c,i)=>{const el=document.createElement('div');el.className='vertex-marker';const m=new maplibregl.Marker({element:el,draggable:true}).setLngLat(c).addTo(map);m.on('dragend',async()=>{snapshot('Edit points');const p=m.getLngLat(),arr=f.type==='boundary'?f.geometry.coordinates[0].slice(0,-1):f.geometry.coordinates;arr[i]=[p.lng,p.lat];if(f.type==='boundary')f.geometry.coordinates=[[...arr,arr[0]]];else if(f.type==='source')f.geometry.coordinates=arr[0];else f.geometry.coordinates=arr;await persist(f);showEditMarkers(f);});markers.push(m);});}
function beginMove(){const f=features.find(x=>x.id===selectedId);if(!f)return;closeSheet('selectSheet');clearMarkers();mode='move';const center=turf.centroid(f).geometry.coordinates,el=document.createElement('div');el.className='move-marker';const m=new maplibregl.Marker({element:el,draggable:true}).setLngLat(center).addTo(map);const original=clone(f.geometry);m.on('dragend',async()=>{snapshot('Move object');const p=m.getLngLat(),dx=p.lng-center[0],dy=p.lat-center[1];f.geometry=shiftGeometry(original,dx,dy);await persist(f);clearMarkers();mode='select';selectFeature(f.id);});markers=[m];setStatus('Drag the green handle. The whole object moves together.');}
function shiftGeometry(g,dx,dy){const h=clone(g);function s(v){if(typeof v?.[0]==='number'){v[0]+=dx;v[1]+=dy}else v?.forEach(s)}s(h.coordinates);return h;}
async function deleteSelected(){const f=features.find(x=>x.id===selectedId);if(!f)return;if(!confirm(`Delete this ${label(f.type)}?`))return;snapshot('Delete object');for(const child of features.filter(x=>x.upstreamId===f.id)){child.upstreamId=null;await put('features',child);}features=features.filter(x=>x.id!==f.id);await remove('features',f.id);clearSelection();refresh();setStatus(`${label(f.type)} deleted. Downstream objects, if any, are now marked unconnected.`);}
function clearMarkers(){markers.forEach(m=>m.remove());markers=[];}
function snapshot(label){undoStack.push({label,features:clone(features)});if(undoStack.length>30)undoStack.shift();redoStack=[];updateUndo();}
async function undo(){if(mode==='create'&&draft?.coords?.length){draft.coords.pop();refreshDraft();return}if(!undoStack.length)return;redoStack.push({features:clone(features)});features=undoStack.pop().features;await replacePersisted();refresh();updateUndo();}
async function redo(){if(!redoStack.length)return;undoStack.push({features:clone(features)});features=redoStack.pop().features;await replacePersisted();refresh();updateUndo();}
async function replacePersisted(){const old=await byProject('features',project.id);for(const f of old)await remove('features',f.id);for(const f of features)await put('features',f);}
function updateUndo(){$('#undoTool').disabled=!undoStack.length;$('#redoTool').disabled=!redoStack.length;}
function label(t){return({main:'Main',submain:'Submain',lateral:'Lateral',source:'Water source',boundary:'Boundary'})[t]||t;}
