(() => {
"use strict";
const store=window.TAGROSpatial,proposal=window.TAGROSpatialProposal;if(!store||!window.L)return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const LABEL={select:"Select",boundary:"Boundary",main:"Main",submain:"Submain",lateral:"Lateral",plant:"Plant",water_source:"Water source",path:"Path",device:"Device"};
const STYLE={boundary:{color:"#d96532",weight:2,fillColor:"#d96532",fillOpacity:.07},main:{color:"#d84a26",weight:6},submain:{color:"#176f87",weight:4},lateral:{color:"#4d7f5e",weight:3},path:{color:"#776d64",weight:3,dashArray:"8 7"},plant:{color:"#39784d",fillColor:"#72a77e",fillOpacity:1,weight:2,radius:6},water_source:{color:"#165f97",fillColor:"#2a8ac9",fillOpacity:1,weight:2,radius:8},device:{color:"#9a5a18",fillColor:"#e8a445",fillOpacity:1,weight:2,radius:6}};
const state={mode:"field",tool:"select",selectedId:null,editingId:null,drawingEdit:false,drawingDrag:null,draft:[],bounds:null,locationMarker:null,measureOn:false,measureRef:null,measureOverlay:null,layoutSourceId:null,layoutPlan:[],layoutPreview:L.layerGroup(),proposalLayers:[]};
const map=L.map("map",{zoomControl:false,doubleClickZoom:true,maxZoom:23,minZoom:3,worldCopyJump:true}).setView([10.2,76.3],8);
const satellite=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{maxNativeZoom:18,maxZoom:23,attribution:"Esri, Maxar, Earthstar Geographics and GIS User Community",pmIgnore:true}).addTo(map);
const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:"© OpenStreetMap contributors",pmIgnore:true});
L.control.layers({Satellite:satellite,Street:street},{},{position:"topleft",collapsed:true}).addTo(map);
state.layoutPreview.addTo(map);state.measureOverlay=L.layerGroup().addTo(map);
map.pm.setGlobalOptions({allowSelfIntersection:false,snappable:true,snapDistance:14,finishOn:"dblclick",finishOnEnter:true,exitModeOnEscape:true,continueDrawing:true});
const layers=new Map();
const visibleKinds=new Set(["boundary","main","submain","lateral","plant","water_source","path","device"]);
function clone(v){return JSON.parse(JSON.stringify(v))}
function latLngs(g){if(!g)return null;if(g.type==="Point")return[g.coordinates[1],g.coordinates[0]];if(g.type==="LineString")return g.coordinates.map(([lng,lat])=>[lat,lng]);if(g.type==="Polygon")return(g.coordinates[0]||[]).map(([lng,lat])=>[lat,lng]);return null}
function geo(layer){return layer?.toGeoJSON?.()?.geometry||null}
function lineCoords(o){return o?.geometry?.type==="LineString"?o.geometry.coordinates||[]:[]}
function lineLength(g){const c=g?.type==="LineString"?g.coordinates:[];let n=0;for(let i=1;i<c.length;i++)n+=map.distance([c[i-1][1],c[i-1][0]],[c[i][1],c[i][0]]);return n}
function polygonArea(g){if(g?.type!=="Polygon")return null;const r=g.coordinates?.[0];if(!r||r.length<3)return null;const R=6378137;let a=0;for(let i=0;i<r.length;i++){const [x1,y1]=r[i],[x2,y2]=r[(i+1)%r.length],d=(x2-x1)*Math.PI/180;a+=d*(2+Math.sin(y1*Math.PI/180)+Math.sin(y2*Math.PI/180))}return Math.abs(a*R*R/2)}
function measureText(o){if(o.geometry?.type==="LineString"){const n=lineLength(o.geometry);return`${n.toFixed(n<100?1:0)} m from real coordinates`}if(o.geometry?.type==="Polygon"){const a=polygonArea(o.geometry),ac=a/4046.8564224;return`${Math.round(a).toLocaleString()} m² · ${ac.toFixed(2)} acres`}if(o.geometry?.type==="Point"){const c=o.geometry.coordinates;return`${c[1].toFixed(6)}, ${c[0].toFixed(6)}`}return""}
function objectById(id){return store.read().objects.find(o=>o.id===id)||null}
function createMapLayer(o){const s={...(STYLE[o.kind]||{color:"#333",weight:3}),className:"tagro-existing"};let l;if(o.geometry.type==="Point")l=L.circleMarker(latLngs(o.geometry),s);else if(o.geometry.type==="Polygon")l=L.polygon(latLngs(o.geometry),s);else l=L.polyline(latLngs(o.geometry),s);l.options.tagroObjectId=o.id;l.options.tagroKind=o.kind;l.bindTooltip(`${o.id} · ${LABEL[o.kind]||o.kind}`,{direction:"top",className:"tagro-tip",opacity:.95});l.on("click",e=>{L.DomEvent.stopPropagation(e);if(state.tool!=="select"&&!state.measureOn)return;if(state.measureOn)return measureObject(o.id);select(o.id)});l.on("pm:update",()=>{const g=geo(l);if(g)store.updateGeometry(o.id,g,"workbench_map_edit")});l.on("pm:dragend",()=>{const g=geo(l);if(g)store.updateGeometry(o.id,g,"workbench_map_drag")});l.addTo(map);if(o.id===state.selectedId)l.getElement?.()?.classList.add("tagro-selected");return l}
function clearLayers(){layers.forEach(l=>{try{map.removeLayer(l)}catch{}});layers.clear()}
function clearProposalLayers(){while(state.proposalLayers.length){const l=state.proposalLayers.pop();try{map.removeLayer(l)}catch{}}}
function renderProposal(){clearProposalLayers();const p=proposal?.current?.();const chip=$("#proposalChip");if(!p?.objects?.length){chip.classList.remove("show");return}for(const s of p.objects){const c=latLngs(s.geometry);if(!c)continue;const opts={color:"#ef8a35",weight:4,dashArray:"9 7",opacity:.9,fillColor:"#ef8a35",fillOpacity:.05,interactive:false,pmIgnore:true,className:"tagro-preview"};let l=s.geometry.type==="Point"?L.circleMarker(c,{...opts,radius:7}):s.geometry.type==="Polygon"?L.polygon(c,opts):L.polyline(c,opts);l.addTo(map);state.proposalLayers.push(l)}$("#proposalTitle").textContent=p.proposal?.summary||"Proposed geometry";$("#proposalNote").textContent=p.note||"Preview only";chip.classList.add("show")}
function renderMap(fit=false){const snap=store.read();clearLayers();snap.objects.filter(o=>visibleKinds.has(o.kind)).forEach(o=>layers.set(o.id,createMapLayer(o)));renderLayoutPreview();renderProposal();if(fit&&layers.size){const g=L.featureGroup([...layers.values()]);const b=g.getBounds();if(b.isValid())map.fitBounds(b.pad(.16),{maxZoom:20})}updateInspector();updateStatus();syncDrawInterference();setTimeout(ensureMapDraw,0)}
function syncDrawInterference(){const busy=state.tool!=="select"||state.measureOn;$("#workspace").classList.toggle("draw-active",busy);layers.forEach(l=>{const el=l.getElement?.();if(el)el.classList.toggle("tagro-selected",l.options.tagroObjectId===state.selectedId)})}
function select(id){if(state.tool!=="select"||state.measureOn)return;state.selectedId=id;updateInspector();syncDrawInterference();renderDrawing()}
function clearSelection(){if(state.editingId){const l=layers.get(state.editingId);try{l?.pm?.disable?.()}catch{}state.editingId=null}state.selectedId=null;state.drawingEdit=false;$("#inspector").classList.remove("show");syncDrawInterference();renderDrawing()}
function updateInspector(){const p=$("#inspector"),o=objectById(state.selectedId);if(!o){p.classList.remove("show");return}$("#selectionName").textContent=`${o.id} · ${LABEL[o.kind]||o.kind}`;$("#selectionMeta").textContent=`${o.state||"described"} · canonical FIELD/DRAWING object`;$("#selectionMeasure").textContent=measureText(o);$("#layoutSelected").classList.toggle("hidden",o.kind!=="submain");$("#editSelected").textContent=(state.editingId===o.id||state.drawingEdit)?"Finish edit":state.mode==="drawing"?"Edit points":"Edit";p.classList.add("show")}
function enableShape(kind){const opt={snappable:true,snapDistance:14,continueDrawing:true};if(kind==="boundary")map.pm.enableDraw("Polygon",opt);else if(["main","submain","lateral","path"].includes(kind))map.pm.enableDraw("Line",opt);else if(["plant","water_source","device"].includes(kind))map.pm.enableDraw("Marker",opt)}
function ensureMapDraw(){if(state.mode!=="field"||state.tool==="select"||state.measureOn)return;try{if(!map.pm.globalDrawModeEnabled())enableShape(state.tool)}catch{enableShape(state.tool)}}
function setTool(kind){stopEdit();state.measureOn=false;state.measureRef=null;$("#measurePanel").classList.remove("show");state.tool=kind;state.draft=[];clearSelection();try{map.pm.disableDraw()}catch{}$$('[data-tool]').forEach(b=>b.classList.toggle("on",b.dataset.tool===kind));$("#toolDock").classList.remove("open");syncActiveChip();syncDrawInterference();if(state.mode==="field"&&kind!=="select")enableShape(kind);renderDrawing();updateStatus()}
function stopTool(){setTool("select")}
function syncActiveChip(){const c=$("#activeChip"),non=state.tool!=="select";c.classList.toggle("show",non);$("#activeToolName").textContent=LABEL[state.tool]||state.tool;const point=["plant","water_source","device"].includes(state.tool);$("#activeToolHint").textContent=point?"Continuous · tap positions · Esc stops":state.mode==="field"?"Continuous · Enter/Finish completes · Esc stops":"Continuous · tap points · Finish completes · Esc stops";$("#finishTool").classList.toggle("hidden",point)}
function sendKey(key){document.dispatchEvent(new KeyboardEvent("keydown",{key,bubbles:true,cancelable:true}));document.dispatchEvent(new KeyboardEvent("keyup",{key,bubbles:true,cancelable:true}))}
function finishCurrent(){if(state.tool==="select")return;if(state.mode==="field")sendKey("Enter");else commitDrawingDraft()}
function stopEdit(){if(state.editingId){const l=layers.get(state.editingId);try{if(l?.pm?.enabled?.())l.pm.disable()}catch{}if(l){const g=geo(l);if(g)store.updateGeometry(state.editingId,g,"workbench_map_edit_finish")}state.editingId=null}state.drawingEdit=false;state.drawingDrag=null}
map.on("pm:create",e=>{if(state.mode!=="field"||state.tool==="select"){try{map.removeLayer(e.layer)}catch{}return}const kind=state.tool,g=geo(e.layer);try{map.removeLayer(e.layer)}catch{}if(!g)return;store.addObject(kind,g,{source_surface:"workbench_field"},"described");state.selectedId=null;setTimeout(()=>{renderMap();ensureMapDraw()},0)});
map.on("click",()=>{if(state.tool==="select"&&!state.measureOn)clearSelection()});
function duplicateSelected(){const o=objectById(state.selectedId);if(!o)return;const z=map.getZoom();function off(c){if(!Array.isArray(c))return c;if(c.length>=2&&typeof c[0]==="number"&&typeof c[1]==="number"){const p=map.project([c[1],c[0]],z),ll=map.unproject([p.x+18,p.y],z);return[ll.lng,ll.lat]}return c.map(off)}const copy=store.addObject(o.kind,{...clone(o.geometry),coordinates:off(o.geometry.coordinates)},{...(o.properties||{}),duplicated_from:o.id},"described");state.selectedId=copy.id;renderMap();renderDrawing();updateInspector()}
function deleteSelected(){if(!state.selectedId)return;const id=state.selectedId;clearSelection();store.removeObject(id)}
function toggleEdit(){const o=objectById(state.selectedId);if(!o)return;if(state.mode==="drawing"){state.drawingEdit=!state.drawingEdit;renderDrawing();updateInspector();return}const l=layers.get(o.id);if(!l?.pm)return;if(state.editingId===o.id){l.pm.disable();const g=geo(l);if(g)store.updateGeometry(o.id,g,"workbench_map_edit_finish");state.editingId=null;renderMap()}else{stopEdit();state.editingId=o.id;l.pm.enable({allowSelfIntersection:false,snappable:true,snapDistance:14});updateInspector()}}
function switchMode(mode){if(!["field","drawing"].includes(mode))return;stopEdit();state.mode=mode;$("#fieldSurface").classList.toggle("on",mode==="field");$("#drawingSurface").classList.toggle("on",mode==="drawing");$("#fieldMode").classList.toggle("on",mode==="field");$("#drawingMode").classList.toggle("on",mode==="drawing");$("#searchBox").classList.toggle("hidden",mode!=="field");$("#locateButton").classList.toggle("hidden",mode!=="field");try{map.pm.disableDraw()}catch{}syncActiveChip();if(mode==="field"){setTimeout(()=>{map.invalidateSize(false);ensureMapDraw()},30)}else renderDrawing();updateInspector();updateStatus()}
// DRAWING projection
const svg=$("#drawingCanvas"),W=1000,H=700,PAD=52;
function pairs(value,out=[]){if(!Array.isArray(value))return out;if(value.length>=2&&typeof value[0]==="number"&&typeof value[1]==="number"){out.push([value[0],value[1]]);return out}value.forEach(x=>pairs(x,out));return out}
function computeBounds(objects){const a=[];objects.forEach(o=>pairs(o.geometry?.coordinates,a));if(!a.length)return null;let minX=Math.min(...a.map(p=>p[0])),maxX=Math.max(...a.map(p=>p[0])),minY=Math.min(...a.map(p=>p[1])),maxY=Math.max(...a.map(p=>p[1]));const m=.0006;if(maxX-minX<m){const c=(maxX+minX)/2;minX=c-m/2;maxX=c+m/2}if(maxY-minY<m){const c=(maxY+minY)/2;minY=c-m/2;maxY=c+m/2}const px=(maxX-minX)*.08,py=(maxY-minY)*.08;return{minX:minX-px,maxX:maxX+px,minY:minY-py,maxY:maxY+py}}
function toXY(ll){const b=state.bounds;return{x:PAD+(ll[0]-b.minX)/(b.maxX-b.minX)*(W-PAD*2),y:PAD+(b.maxY-ll[1])/(b.maxY-b.minY)*(H-PAD*2)}}
function toLL(p){const b=state.bounds;return[b.minX+(p.x-PAD)/(W-PAD*2)*(b.maxX-b.minX),b.maxY-(p.y-PAD)/(H-PAD*2)*(b.maxY-b.minY)]}
function localPoint(e){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const m=svg.getScreenCTM();if(!m)return{x:0,y:0};const q=p.matrixTransform(m.inverse());return{x:Math.max(PAD,Math.min(W-PAD,q.x)),y:Math.max(PAD,Math.min(H-PAD,q.y))}}
function objectCoordinates(o){if(o.geometry.type==="Point")return[o.geometry.coordinates];if(o.geometry.type==="LineString")return o.geometry.coordinates||[];if(o.geometry.type==="Polygon"){const r=o.geometry.coordinates?.[0]||[];if(r.length>1&&r[0][0]===r[r.length-1][0]&&r[0][1]===r[r.length-1][1])return r.slice(0,-1);return r}return[]}
function geomFrom(kind,ps){if(["plant","water_source","device"].includes(kind))return{type:"Point",coordinates:ps[0]};if(kind==="boundary"){const r=[...ps];if(r.length&&(r[0][0]!==r[r.length-1][0]||r[0][1]!==r[r.length-1][1]))r.push([...r[0]]);return{type:"Polygon",coordinates:[r]}}return{type:"LineString",coordinates:ps}}
function sEl(tag,attrs={}){const n=document.createElementNS("http://www.w3.org/2000/svg",tag);Object.entries(attrs).forEach(([k,v])=>n.setAttribute(k,String(v)));return n}
function renderDrawing(){if(state.mode!=="drawing")return;const objs=store.read().objects.filter(o=>visibleKinds.has(o.kind));state.bounds=computeBounds(objs);svg.replaceChildren();for(let x=50;x<W;x+=50)svg.append(sEl("line",{x1:x,y1:0,x2:x,y2:H,class:"grid-line"}));for(let y=50;y<H;y+=50)svg.append(sEl("line",{x1:0,y1:y,x2:W,y2:y,class:"grid-line"}));$("#drawingEmpty").hidden=!!state.bounds;if(!state.bounds)return;for(const o of objs){const c=objectCoordinates(o),pts=c.map(toXY);if(!pts.length)continue;let n;if(o.geometry.type==="Point")n=sEl("circle",{cx:pts[0].x,cy:pts[0].y,r:o.kind==="water_source"?9:7,class:`draw-object point ${o.kind}`});else if(o.geometry.type==="Polygon")n=sEl("polygon",{points:pts.map(p=>`${p.x},${p.y}`).join(" "),class:`draw-object ${o.kind}`});else n=sEl("polyline",{points:pts.map(p=>`${p.x},${p.y}`).join(" "),class:`draw-object ${o.kind}`});n.dataset.objectId=o.id;if(o.id===state.selectedId)n.classList.add("selected");n.style.pointerEvents=(state.tool==="select"||state.measureOn||state.drawingEdit)?"auto":"none";n.addEventListener("pointerup",e=>{if(state.tool!=="select"&&!state.measureOn)return;e.stopPropagation();if(state.measureOn)measureObject(o.id);else select(o.id)});svg.append(n);const lab=sEl("text",{x:pts[0].x+8,y:pts[0].y-8,class:"draw-label"});lab.textContent=o.id;svg.append(lab);if(state.drawingEdit&&state.selectedId===o.id){pts.forEach((p,i)=>{const h=sEl("circle",{cx:p.x,cy:p.y,r:7,class:"draw-handle"});h.addEventListener("pointerdown",e=>{e.stopPropagation();h.setPointerCapture?.(e.pointerId);state.drawingDrag={id:o.id,index:i,pointerId:e.pointerId,geometry:null}});svg.append(h)})}}
for(const row of state.layoutPlan){const pts=row.geometry.coordinates.map(toXY);svg.append(sEl("polyline",{points:pts.map(p=>`${p.x},${p.y}`).join(" "),class:"draw-draft"}))}
if(state.draft.length){const pts=state.draft.map(toXY);if(pts.length>1)svg.append(sEl("polyline",{points:pts.map(p=>`${p.x},${p.y}`).join(" "),class:"draw-draft"}));pts.forEach(p=>svg.append(sEl("circle",{cx:p.x,cy:p.y,r:6,class:"draw-draft-point"})))}updateStatus()}
svg.addEventListener("pointerup",e=>{if(state.drawingDrag)return;if(state.mode!=="drawing"||state.measureOn)return;if(state.tool==="select"){if(e.target===svg)clearSelection();return}if(!state.bounds)return;const ll=toLL(localPoint(e));if(["plant","water_source","device"].includes(state.tool)){store.addObject(state.tool,{type:"Point",coordinates:ll},{source_surface:"workbench_drawing"},"described");state.selectedId=null;renderDrawing();return}state.draft.push(ll);renderDrawing()});
svg.addEventListener("pointermove",e=>{const d=state.drawingDrag;if(!d||!state.bounds)return;const o=objectById(d.id);if(!o)return;const ps=objectCoordinates(o);if(!ps[d.index])return;ps[d.index]=toLL(localPoint(e));d.geometry=geomFrom(o.kind,ps);const hs=$$(".draw-handle");const h=hs[d.index];if(h){const p=toXY(ps[d.index]);h.setAttribute("cx",p.x);h.setAttribute("cy",p.y)}});
svg.addEventListener("pointerup",()=>{const d=state.drawingDrag;if(!d)return;if(d.geometry)store.updateGeometry(d.id,d.geometry,"workbench_drawing_vertex_edit");state.drawingDrag=null;renderDrawing()},true);
function commitDrawingDraft(){if(state.mode!=="drawing"||state.tool==="select"||!state.draft.length)return;if(state.tool==="boundary"&&state.draft.length<3)return;if(["main","submain","lateral","path"].includes(state.tool)&&state.draft.length<2)return;store.addObject(state.tool,geomFrom(state.tool,state.draft),{source_surface:"workbench_drawing"},"described");state.draft=[];state.selectedId=null;renderDrawing()}
// Measure / spacing
function objSegments(o){const c=objectCoordinates(o);if(!c.length)return[];if(o.geometry.type==="Point")return[{a:c[0],b:c[0],point:true}];const out=[];for(let i=1;i<c.length;i++)out.push({a:c[i-1],b:c[i]});if(o.geometry.type==="Polygon"&&c.length>2)out.push({a:c[c.length-1],b:c[0]});return out}
function closestOn(P,A,B){const vx=B.x-A.x,vy=B.y-A.y,wx=P.x-A.x,wy=P.y-A.y,c=vx*vx+vy*vy,t=c?Math.max(0,Math.min(1,(vx*wx+vy*wy)/c)):0;return L.point(A.x+vx*t,A.y+vy*t)}
function distanceObjects(a,b){const z=map.getZoom(),cand=[];function add(p,A,B,flip=false){const P=map.project([p[1],p[0]],z),AA=map.project([A[1],A[0]],z),BB=map.project([B[1],B[0]],z),Q=closestOn(P,AA,BB),d=P.distanceTo(Q);cand.push(flip?{d,p:Q,q:P}:{d,p:P,q:Q})}for(const A of objSegments(a))for(const B of objSegments(b)){add(A.a,B.a,B.b);add(A.b,B.a,B.b);add(B.a,A.a,A.b,true);add(B.b,A.a,A.b,true)}cand.sort((x,y)=>x.d-y.d);const x=cand[0];if(!x)return null;const p=map.unproject(x.p,z),q=map.unproject(x.q,z);return{distance:map.distance(p,q),p,q}}
function activateMeasure(){stopTool();state.measureOn=true;state.measureRef=state.selectedId||null;clearSelection();state.measureOverlay.clearLayers();$("#measurePanel").classList.add("show");$("#measureText").textContent=state.measureRef?`Reference ${state.measureRef}. Click another object.`:"Click the first object, then another object.";syncDrawInterference();renderDrawing()}
function closeMeasure(){state.measureOn=false;state.measureRef=null;state.measureOverlay.clearLayers();$("#measurePanel").classList.remove("show");syncDrawInterference();renderDrawing()}
function measureObject(id){if(!state.measureRef){state.measureRef=id;$("#measureText").textContent=`Reference ${id}. Click another object.`;return}if(id===state.measureRef)return;const a=objectById(state.measureRef),b=objectById(id),m=distanceObjects(a,b);if(!m)return;state.measureOverlay.clearLayers();L.polyline([m.p,m.q],{color:"#111",weight:2,dashArray:"5 4",interactive:false,pmIgnore:true}).addTo(state.measureOverlay);$("#measureText").textContent=`${a.id} ↔ ${b.id}: ${m.distance.toFixed(m.distance<10?2:1)} m shortest distance.`}
function familySpacing(){const p=objectById(state.measureRef||state.selectedId);if(!p||!["main","submain"].includes(p.kind)){ $("#measureText").textContent="Choose a Main or Submain as the family reference.";return}const children=store.read().objects.filter(o=>o.kind===(p.kind==="main"?"submain":"lateral")).filter(o=>o.properties?.network?.parent_id===p.id);if(children.length<2){$("#measureText").textContent=`${p.id}: fewer than two explicitly tied child pipes. Nothing to summarize.`;return}const pc=lineCoords(p);function nearestAlong(o){const ends=lineCoords(o);if(!ends.length)return null;const target=ends[0];let best={d:Infinity,along:0},cum=0,z=map.getZoom(),P=map.project([target[1],target[0]],z);for(let i=1;i<pc.length;i++){const A=map.project([pc[i-1][1],pc[i-1][0]],z),B=map.project([pc[i][1],pc[i][0]],z),Q=closestOn(P,A,B),ll=map.unproject(Q,z),d=map.distance([target[1],target[0]],ll),seg=map.distance([pc[i-1][1],pc[i-1][0]],[pc[i][1],pc[i][0]]),t=A.distanceTo(B)?A.distanceTo(Q)/A.distanceTo(B):0;if(d<best.d)best={d,along:cum+Math.max(0,Math.min(1,t))*seg};cum+=seg}return best.along}const vals=children.map(nearestAlong).filter(Number.isFinite).sort((a,b)=>a-b),g=[];for(let i=1;i<vals.length;i++)g.push(vals[i]-vals[i-1]);if(!g.length)return;const avg=g.reduce((a,b)=>a+b,0)/g.length;$("#measureText").textContent=`${p.id}: ${g.length} spacings · min ${Math.min(...g).toFixed(2)} m · avg ${avg.toFixed(2)} m · max ${Math.max(...g).toFixed(2)} m.`}
// Lateral layout
function bearing(a,b){const p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,d=(b[0]-a[0])*Math.PI/180,y=Math.sin(d)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(d);return(Math.atan2(y,x)*180/Math.PI+360)%360}
function destination(a,deg,m){const R=6371008.8,d=m/R,t=deg*Math.PI/180,p1=a[1]*Math.PI/180,l1=a[0]*Math.PI/180,p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(t)),l2=l1+Math.atan2(Math.sin(t)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return[((l2*180/Math.PI+540)%360)-180,p2*180/Math.PI]}
function pointAlong(coords,d){let n=0;for(let i=1;i<coords.length;i++){const s=map.distance([coords[i-1][1],coords[i-1][0]],[coords[i][1],coords[i][0]]);if(n+s>=d){const t=s?(d-n)/s:0;return[coords[i-1][0]+(coords[i][0]-coords[i-1][0])*t,coords[i-1][1]+(coords[i][1]-coords[i-1][1])*t]}n+=s}return coords[coords.length-1]}
function clipEnd(anchor,end,boundary){if(!boundary)return end;const z=map.getZoom(),P=map.project([anchor[1],anchor[0]],z),E=map.project([end[1],end[0]],z),dir=L.point(E.x-P.x,E.y-P.y),ring=objectCoordinates(boundary).map(c=>map.project([c[1],c[0]],z));const cross=(a,b)=>a.x*b.y-a.y*b.x,sub=(a,b)=>L.point(a.x-b.x,a.y-b.y),hits=[];for(let i=0;i<ring.length;i++){const A=ring[i],B=ring[(i+1)%ring.length],edge=sub(B,A),den=cross(dir,edge);if(Math.abs(den)<1e-9)continue;const ap=sub(A,P),t=cross(ap,edge)/den,u=cross(ap,dir)/den;if(t>.001&&t<=1.0001&&u>=-1e-7&&u<=1+1e-7)hits.push(t)}if(!hits.length)return end;hits.sort((a,b)=>a-b);const t=hits[0],Q=L.point(P.x+dir.x*t,P.y+dir.y*t),ll=map.unproject(Q,z);return[ll.lng,ll.lat]}
function existingFeedNear(anchor,sub,threshold){return store.read().objects.filter(o=>o.kind==="lateral").some(o=>{if(o.properties?.network?.parent_id&&o.properties.network.parent_id!==sub.id)return false;const c=lineCoords(o);if(!c.length)return false;return Math.min(map.distance([anchor[1],anchor[0]],[c[0][1],c[0][0]]),map.distance([anchor[1],anchor[0]],[c[c.length-1][1],c[c.length-1][0]]))<=threshold})}
function openLayout(){const o=objectById(state.selectedId);if(!o||o.kind!=="submain"){updateStatus("Select a Submain first, then Layout Laterals.");return}state.layoutSourceId=o.id;state.layoutPlan=[];$("#layoutSource").textContent=o.id;const c=lineCoords(o),total=lineLength(o.geometry);$("#layoutEnd").placeholder=`full ${total.toFixed(1)} m`;if(c.length>=2)$("#layoutBearing").value=((bearing(c[0],c[c.length-1])+90)%360).toFixed(1);const clip=$("#layoutClip");clip.innerHTML='<option value="">None · free run</option>';const bs=store.read().objects.filter(x=>x.kind==="boundary");bs.forEach(b=>{const op=document.createElement("option");op.value=b.id;op.textContent=`${b.id} · Boundary`;clip.append(op)});if(bs.length===1)clip.value=bs[0].id;$("#layoutPanel").classList.add("show");$("#layoutStatus").textContent=`${o.id} length ${total.toFixed(1)} m. Preview before Create.`;$("#createLayout").disabled=true;$("#toolDock").classList.remove("open");clearSelection()}
function previewLayout(){const sub=objectById(state.layoutSourceId);if(!sub)return;const c=lineCoords(sub),total=lineLength(sub.geometry),spacing=+$("#layoutSpacing").value,start=Math.max(0,+$("#layoutStart").value||0),endRaw=$("#layoutEnd").value,end=endRaw===""?total:Math.min(total,Math.max(start,+endRaw||0)),run=+$("#layoutLength").value,b=((+$("#layoutBearing").value%360)+360)%360,both=$("#layoutSide").value==="both",boundary=objectById($("#layoutClip").value),skip=$("#layoutSkip").checked;if(!(spacing>0&&run>0)){ $("#layoutStatus").textContent="Spacing and lateral length must be greater than zero.";return}state.layoutPlan=[];const threshold=Math.min(1.5,spacing*.25);for(let d=start;d<=end+.001&&state.layoutPlan.length<120;d+=spacing){const a=pointAlong(c,d);if(!a)continue;if(skip&&existingFeedNear(a,sub,threshold))continue;for(const dir of both?[b,(b+180)%360]:[b]){let e=destination(a,dir,run);e=clipEnd(a,e,boundary);const len=map.distance([a[1],a[0]],[e[1],e[0]]);if(len<.4)continue;state.layoutPlan.push({geometry:{type:"LineString",coordinates:[a,e]},length:len,bearing:dir,along:d})}}renderLayoutPreview();renderDrawing();const n=state.layoutPlan.length,meters=state.layoutPlan.reduce((s,x)=>s+x.length,0);$("#createLayout").disabled=!n;$("#layoutStatus").textContent=n?`Preview ${n} lateral${n===1?"":"s"} · ${meters.toFixed(1)} m${boundary?` · clipped to ${boundary.id}`:" · free run"}. Orange dashed lines are preview only.`:"No valid runs found."}
function renderLayoutPreview(){state.layoutPreview.clearLayers();if(state.mode!=="field")return;state.layoutPlan.forEach(r=>L.polyline(latLngs(r.geometry),{color:"#ef8a35",weight:3,dashArray:"7 6",opacity:.9,interactive:false,pmIgnore:true,className:"tagro-preview"}).addTo(state.layoutPreview))}
function createLayout(){const sub=objectById(state.layoutSourceId);if(!sub||!state.layoutPlan.length)return;const n=state.layoutPlan.length;for(const r of state.layoutPlan)store.addObject("lateral",r.geometry,{source_surface:"workbench_layout",network:{parent_id:sub.id,parent_source:"layout_from_selected_submain"},layout:{spacing_m:+$("#layoutSpacing").value,bearing_deg:r.bearing,along_submain_m:r.along}},"described");state.layoutPlan=[];state.layoutPreview.clearLayers();$("#createLayout").disabled=true;$("#layoutStatus").textContent=`Created ${n} laterals tied to ${sub.id}. Tool stays open; preview again to add more.`;renderDrawing()}
function clearLayout(){state.layoutPlan=[];state.layoutPreview.clearLayers();$("#createLayout").disabled=true;$("#layoutStatus").textContent="Preview cleared. No geometry was created.";renderDrawing()}
function closeLayout(){clearLayout();state.layoutSourceId=null;$("#layoutPanel").classList.remove("show")}
function updateStatus(custom){if(custom){$("#status").textContent=custom;return}const s=store.read(),counts={};s.objects.forEach(o=>counts[o.kind]=(counts[o.kind]||0)+1);const p=[];if(counts.boundary)p.push(`${counts.boundary} boundary`);if(counts.main)p.push(`${counts.main} main`);if(counts.submain)p.push(`${counts.submain} submain`);if(counts.lateral)p.push(`${counts.lateral} lateral`);if(counts.plant)p.push(`${counts.plant} plant${counts.plant===1?"":"s"}`);$("#status").textContent=`${state.mode.toUpperCase()} · ${state.tool==="select"?"Select":`${LABEL[state.tool]} continuous`} · ${p.length?p.join(" · "):"blank job · nothing assumed"}`}
async function searchPlace(){const v=$("#searchInput").value.trim();if(!v)return;const c=v.match(/^\s*(-?\d+(?:\.\d+)?)\s*[, ]\s*(-?\d+(?:\.\d+)?)\s*$/);if(c){map.setView([+c[1],+c[2]],19);return}try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(v)}`),d=await r.json();if(d?.[0])map.setView([+d[0].lat,+d[0].lon],19)}catch{}}
// UI bindings
$("#fieldMode").onclick=()=>switchMode("field");$("#drawingMode").onclick=()=>switchMode("drawing");$("#workButton").onclick=()=>$("#toolDock").classList.toggle("open");$("#closeTools").onclick=()=>$("#toolDock").classList.remove("open");$$('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$("#stopTool").onclick=stopTool;$("#finishTool").onclick=finishCurrent;$("#closeInspector").onclick=clearSelection;$("#editSelected").onclick=toggleEdit;$("#duplicateSelected").onclick=duplicateSelected;$("#deleteSelected").onclick=deleteSelected;$("#layoutSelected").onclick=openLayout;$("#layoutTool").onclick=openLayout;$("#measureTool").onclick=activateMeasure;$("#closeMeasure").onclick=closeMeasure;$("#newMeasure").onclick=()=>{state.measureRef=null;state.measureOverlay.clearLayers();$("#measureText").textContent="Click the first object, then another object."};$("#familyMeasure").onclick=familySpacing;$("#closeLayout").onclick=closeLayout;$("#previewLayout").onclick=previewLayout;$("#createLayout").onclick=createLayout;$("#clearLayout").onclick=clearLayout;$("#flipLayout").onclick=()=>{$("#layoutBearing").value=((+$("#layoutBearing").value+180)%360).toFixed(1);previewLayout()};$("#acceptProposal").onclick=()=>{const r=proposal?.accept?.();if(r?.ok){renderMap();renderDrawing()}};$("#clearProposal").onclick=()=>{proposal?.clear?.();renderMap()};$("#searchButton").onclick=searchPlace;$("#searchInput").onkeydown=e=>{if(e.key==="Enter")searchPlace()};$("#locateButton").onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{const ll=[p.coords.latitude,p.coords.longitude];map.setView(ll,19);if(state.locationMarker)state.locationMarker.setLatLng(ll);else state.locationMarker=L.circleMarker(ll,{radius:6,weight:2,color:"#fff",fillColor:"#1677ff",fillOpacity:1,interactive:false,pmIgnore:true}).addTo(map)},()=>{},{enableHighAccuracy:true,timeout:12000,maximumAge:30000});
document.addEventListener("keydown",e=>{if(e.key==="Escape"){if($("#layoutPanel").classList.contains("show"))return closeLayout();if(state.measureOn)return closeMeasure();if(state.tool!=="select")return stopTool();clearSelection()}if(e.key==="Enter"&&state.mode==="drawing"&&state.tool!=="select"){e.preventDefault();commitDrawingDraft()}});
window.addEventListener("tagro:spatial-change",()=>{renderMap();renderDrawing()});window.addEventListener("tagro:spatial-preview-change",()=>renderMap());
renderMap(true);renderDrawing();syncActiveChip();updateStatus();
})();