import {DEFAULT_LAYOUT} from '../config/layout.default.js';
import {TagroStore} from './store.js';
import {COMPONENTS,renderComponent} from '../library/components.js';
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)];
const clone=x=>JSON.parse(JSON.stringify(x));
const saved=localStorage.getItem('tagro-irrigation-layout');
let layout=saved?JSON.parse(saved):clone(DEFAULT_LAYOUT);
let current=layout.pages[0].id;
let layoutMode=false,dragId=null;
const store=new TagroStore();
function save(){localStorage.setItem('tagro-irrigation-layout',JSON.stringify(layout))}
function page(){return layout.pages.find(p=>p.id===current)||layout.pages[0]}
function applySettings(){const s=layout.settings;document.documentElement.style.setProperty('--tile-scale',s.tileScale);document.documentElement.style.setProperty('--left-width',`${s.leftWidth}px`);document.documentElement.style.setProperty('--right-width',`${s.rightWidth}px`);qs('#app').classList.toggle('left-hidden',!s.leftVisible);qs('#app').classList.toggle('right-hidden',!s.rightVisible);qs('#tileScale').value=s.tileScale;qs('#leftWidth').value=s.leftWidth;qs('#rightWidth').value=s.rightWidth}
function renderNav(){qs('#pageNav').innerHTML=layout.pages.map((p,i)=>`<button class="page-link ${p.id===current?'active':''}" data-page="${p.id}"><span class="page-index">${String(i+1).padStart(2,'0')}</span>${p.label}</button>`).join('');qs('#mobileNav').style.setProperty('--mobile-count',Math.min(layout.pages.length,5));qs('#mobileNav').innerHTML=layout.pages.map((p,i)=>`<button class="mobile-nav-button ${p.id===current?'active':''}" data-page="${p.id}"><span>${i+1}</span><small>${p.label}</small></button>`).join('');qsa('[data-page]').forEach(b=>b.onclick=()=>{current=b.dataset.page;render()})}
function bindFields(){qsa('[data-path]').forEach(el=>{const v=store.get().data[el.dataset.path];if(v!==undefined)el.value=v;el.onchange=()=>store.set(el.dataset.path,el.value,{source:el.closest('.dock')?.dataset.component||'ui',status:'observed'})})}
function renderDocks(){const p=page();qs('#dockGrid').innerHTML=p.components.map(id=>renderComponent(id,{store,layout,page:p})).join('');qsa('.dock').forEach(d=>{d.draggable=layoutMode;d.ondragstart=()=>{dragId=d.dataset.component;d.classList.add('dragging')};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const target=d.dataset.component;if(!dragId||dragId===target)return;const a=p.components.indexOf(dragId),b=p.components.indexOf(target);p.components.splice(a,1);p.components.splice(b,0,dragId);save();renderDocks()}});qsa('[data-action]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const dock=btn.closest('.dock'),id=dock.dataset.component,act=btn.dataset.action;if(act==='remove'){page().components=page().components.filter(x=>x!==id);save();renderDocks()}if(act==='compact')dock.classList.toggle('compact');if(act==='size'){const spans=[4,6,8,12];const hit=spans.find(s=>dock.classList.contains('span-'+s))||6;const next=spans[(spans.indexOf(hit)+1)%spans.length];spans.forEach(s=>dock.classList.remove('span-'+s));dock.classList.add('span-'+next)}});bindFields()}
function renderContext(){const data=store.get().data,entries=Object.entries(data).slice(-8).reverse();qs('#contextPanel').innerHTML=entries.length?entries.map(([k,v])=>`<div class="context-card"><b>${k}</b><span>${v||'—'}</span></div>`).join(''):'<div class="context-card"><b>No observations yet</b><span>Information entered in any dock appears here as shared farm context.</span></div>';const ripples=store.get().ripples.slice(0,6);qs('#ripplePanel').innerHTML=ripples.length?ripples.map(r=>`<div class="ripple-item"><b>${r.from}</b><span>→ ${r.targets.join(' · ')}</span></div>`).join(''):'<div class="ripple-item"><b>No ripple yet</b><span>Changes will show affected planes here.</span></div>'}
function renderLibrary(){qs('#libraryGrid').innerHTML=Object.entries(COMPONENTS).map(([id,c])=>`<button class="library-item" data-add="${id}"><b>${c.icon||'·'} ${c.title}</b><span>${c.subtitle||''}</span></button>`).join('');qsa('[data-add]').forEach(b=>b.onclick=()=>{if(!page().components.includes(b.dataset.add))page().components.push(b.dataset.add);save();renderDocks()})}
function render(){const p=page();qs('#pageEyebrow').textContent=p.eyebrow;qs('#pageTitle').textContent=p.label;qs('#pageDescription').textContent=p.description;renderNav();renderDocks();renderContext();applySettings()}
qs('#toggleLeft').onclick=()=>{layout.settings.leftVisible=!layout.settings.leftVisible;save();applySettings()};qs('#toggleRight').onclick=()=>{layout.settings.rightVisible=!layout.settings.rightVisible;save();applySettings()};qs('#layoutMode').onclick=()=>{layoutMode=!layoutMode;document.body.classList.toggle('layout-mode',layoutMode);qs('#layoutMode').textContent=layoutMode?'Done':'Arrange';renderDocks()};qs('#openLibrary').onclick=()=>qs('#libraryDrawer').classList.add('open');qs('#closeLibrary').onclick=()=>qs('#libraryDrawer').classList.remove('open');qs('#libraryDrawer').onclick=e=>{if(e.target.id==='libraryDrawer')e.currentTarget.classList.remove('open')};qs('#tileScale').oninput=e=>{layout.settings.tileScale=+e.target.value;save();applySettings()};qs('#leftWidth').oninput=e=>{layout.settings.leftWidth=+e.target.value;save();applySettings()};qs('#rightWidth').oninput=e=>{layout.settings.rightWidth=+e.target.value;save();applySettings()};qs('#movePageLeft').onclick=()=>movePage(-1);qs('#movePageRight').onclick=()=>movePage(1);function movePage(delta){const i=layout.pages.findIndex(p=>p.id===current),j=Math.max(0,Math.min(layout.pages.length-1,i+delta));if(i===j)return;const [p]=layout.pages.splice(i,1);layout.pages.splice(j,0,p);save();render()}
qs('#resetLayout').onclick=()=>{layout=clone(DEFAULT_LAYOUT);current=layout.pages[0].id;save();render();renderLibrary()};qs('#exportLayout').onclick=()=>{const blob=new Blob([JSON.stringify(layout,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tagro-irrigation-layout.json';a.click();URL.revokeObjectURL(a.href)};
store.on(()=>{renderContext();if(current==='review')renderDocks()});
renderLibrary();render();
