import {DEFAULT_LAYOUT} from '../config/layout.default.js';
import {TagroStore} from './store.js';
import {COMPONENTS,renderComponent} from '../library/components.js';
const qs=s=>document.querySelector(s), qsa=s=>[...document.querySelectorAll(s)], clone=x=>JSON.parse(JSON.stringify(x));
const saved=localStorage.getItem('tagro-irrigation-layout');
let layout=saved?JSON.parse(saved):clone(DEFAULT_LAYOUT), current=layout.pages[0].id, layoutMode=false, dragId=null;
const store=new TagroStore();
function save(){localStorage.setItem('tagro-irrigation-layout',JSON.stringify(layout))}
function page(){return layout.pages.find(p=>p.id===current)||layout.pages[0]}
function applySettings(){const s=layout.settings;document.documentElement.style.setProperty('--tile-scale',s.tileScale);document.documentElement.style.setProperty('--left-width',`${s.leftWidth}px`);document.documentElement.style.setProperty('--right-width',`${s.rightWidth}px`);qs('#app').classList.toggle('left-hidden',!s.leftVisible);qs('#app').classList.toggle('right-hidden',!s.rightVisible);qs('#tileScale').value=s.tileScale;qs('#leftWidth').value=s.leftWidth;qs('#rightWidth').value=s.rightWidth}
function renderNav(){qs('#pageNav').innerHTML=layout.pages.map((p,i)=>`<button class="page-link ${p.id===current?'active':''}" data-page="${p.id}"><span class="page-index">${String(i+1).padStart(2,'0')}</span>${p.label}</button>`).join('');qs('#mobileNav').style.setProperty('--mobile-count',Math.min(layout.pages.length,5));qs('#mobileNav').innerHTML=layout.pages.map((p,i)=>`<button class="mobile-nav-button ${p.id===current?'active':''}" data-page="${p.id}"><span>${i+1}</span><small>${p.label}</small></button>`).join('');qsa('[data-page]').forEach(b=>b.onclick=()=>{current=b.dataset.page;render()})}
function bindFields(){qsa('[data-path]').forEach(el=>{const v=store.value(el.dataset.path);if(v!==undefined)el.value=v;el.onchange=()=>store.set(el.dataset.path,el.value,{source:el.closest('.dock')?.dataset.component||'ui',status:'observed'})})}
function bindLocation(){const fn=()=>{if(!navigator.geolocation){alert('Location is not available on this device.');return}navigator.geolocation.getCurrentPosition(pos=>{const v=`${pos.coords.latitude.toFixed(6)}, ${pos.coords.longitude.toFixed(6)}`;store.set('location.coordinates',v,{source:'device-gps',status:'observed'});const el=qs('[data-path="location.coordinates"]');if(el)el.value=v},()=>alert('Location permission was not available.'))};const a=qs('#captureLocation'),b=qs('#locateField');if(a)a.onclick=fn;if(b)b.onclick=fn}
function sketchState(){try{return JSON.parse(store.value('field.sketch')||'{}')}catch{return{}}}
function bindSketch(){const svg=qs('#fieldSketchSvg');if(!svg)return;let s=sketchState();if(!Array.isArray(s.points))s={points:[],closed:false,measure:true};let dragging=-1;
 const xy=e=>{const r=svg.getBoundingClientRect();return{x:(e.clientX-r.left)*600/r.width,y:(e.clientY-r.top)*320/r.height}};
 const distance=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
 const draw=()=>{const pts=s.points.map(p=>`${p.x},${p.y}`);if(s.closed&&pts.length>2)pts.push(pts[0]);qs('#sketchLine').setAttribute('points',pts.join(' '));qs('#sketchPoints').innerHTML=s.points.map((p,i)=>`<circle class="sketch-point" data-i="${i}" cx="${p.x}" cy="${p.y}" r="8"></circle>`).join('');const d=s.points.slice(1).reduce((n,p,i)=>n+distance(s.points[i],p),0)+(s.closed&&s.points.length>2?distance(s.points.at(-1),s.points[0]):0);qs('#sketchReadout').textContent=s.measure&&s.points.length>1?`${s.points.length} points · relative perimeter ${d.toFixed(0)} sketch units · drag any point to adjust`:`${s.points.length} points · tap to add, drag to adjust`;qs('#sketchMeasure').textContent=`Measurements: ${s.measure?'on':'off'}`;store.set('field.sketch',JSON.stringify(s),{source:'fieldSketch',status:'observed'});};
 svg.onpointerdown=e=>{const c=e.target.closest?.('.sketch-point');if(c){dragging=+c.dataset.i;svg.setPointerCapture(e.pointerId);return}if(s.closed)return;const p=xy(e);s.points.push({x:+p.x.toFixed(1),y:+p.y.toFixed(1)});draw()};
 svg.onpointermove=e=>{if(dragging<0)return;const p=xy(e);s.points[dragging]={x:Math.max(0,Math.min(600,p.x)),y:Math.max(0,Math.min(320,p.y))};draw()};
 svg.onpointerup=()=>dragging=-1;
 qs('#sketchUndo').onclick=()=>{s.points.pop();s.closed=false;draw()};qs('#sketchClose').onclick=()=>{if(s.points.length>=3)s.closed=true;draw()};qs('#sketchClear').onclick=()=>{s={points:[],closed:false,measure:s.measure};draw()};qs('#sketchMeasure').onclick=()=>{s.measure=!s.measure;draw()};
 const pts=s.points.map(p=>`${p.x},${p.y}`);if(s.closed&&pts.length>2)pts.push(pts[0]);qs('#sketchLine').setAttribute('points',pts.join(' '));qs('#sketchPoints').innerHTML=s.points.map((p,i)=>`<circle class="sketch-point" data-i="${i}" cx="${p.x}" cy="${p.y}" r="8"></circle>`).join('');qs('#sketchReadout').textContent=s.points.length?`${s.points.length} points saved · drag any point to adjust`:'Tap to add points. Drag a point to move it. This is rough field intelligence, not surveyed truth.';qs('#sketchMeasure').textContent=`Measurements: ${s.measure?'on':'off'}`;
}
function renderDocks(){const p=page();qs('#dockGrid').innerHTML=p.components.map(id=>renderComponent(id,{store,layout,page:p})).join('');qsa('.dock').forEach(d=>{d.draggable=layoutMode;d.ondragstart=()=>{dragId=d.dataset.component;d.classList.add('dragging')};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const target=d.dataset.component;if(!dragId||dragId===target)return;const a=p.components.indexOf(dragId),b=p.components.indexOf(target);p.components.splice(a,1);p.components.splice(b,0,dragId);save();renderDocks()}});qsa('[data-action]').forEach(btn=>btn.onclick=e=>{e.stopPropagation();const dock=btn.closest('.dock'),id=dock.dataset.component,act=btn.dataset.action;if(act==='remove'){page().components=page().components.filter(x=>x!==id);save();renderDocks()}if(act==='compact')dock.classList.toggle('compact');if(act==='size'){const spans=[4,6,8,12],hit=spans.find(s=>dock.classList.contains('span-'+s))||6,next=spans[(spans.indexOf(hit)+1)%spans.length];spans.forEach(s=>dock.classList.remove('span-'+s));dock.classList.add('span-'+next)}});bindFields();bindLocation();bindSketch()}
function renderContext(){const entries=Object.entries(store.get().data).slice(-10).reverse();qs('#contextPanel').innerHTML=entries.length?entries.map(([k,obj])=>`<div class="context-card"><b>${k}</b><span>${String(obj.value||'—').slice(0,90)}</span><small>${obj.status||'observed'} · ${obj.source||'ui'}</small></div>`).join(''):'<div class="context-card"><b>No observations yet</b><span>Information entered in any dock appears here as shared farm context.</span></div>';const ripples=store.get().ripples.slice(0,6);qs('#ripplePanel').innerHTML=ripples.length?ripples.map(r=>`<div class="ripple-item"><b>${r.from}</b><span>→ ${r.targets.join(' · ')}</span></div>`).join(''):'<div class="ripple-item"><b>No ripple yet</b><span>Changes will show affected planes here.</span></div>'}
function renderLibrary(){qs('#libraryGrid').innerHTML=Object.entries(COMPONENTS).map(([id,c])=>`<button class="library-item" data-add="${id}"><b>${c.icon||'·'} ${c.title}</b><span>${c.subtitle||''}</span></button>`).join('');qsa('[data-add]').forEach(b=>b.onclick=()=>{if(!page().components.includes(b.dataset.add))page().components.push(b.dataset.add);save();renderDocks()})}
function render(){const p=page();qs('#pageEyebrow').textContent=p.eyebrow;qs('#pageTitle').textContent=p.label;qs('#pageDescription').textContent=p.description;renderNav();renderDocks();renderContext();applySettings()}
qs('#toggleLeft').onclick=()=>{layout.settings.leftVisible=!layout.settings.leftVisible;save();applySettings()};qs('#toggleRight').onclick=()=>{layout.settings.rightVisible=!layout.settings.rightVisible;save();applySettings()};qs('#layoutMode').onclick=()=>{layoutMode=!layoutMode;document.body.classList.toggle('layout-mode',layoutMode);qs('#layoutMode').textContent=layoutMode?'Done':'Arrange';renderDocks()};qs('#openLibrary').onclick=()=>qs('#libraryDrawer').classList.add('open');qs('#closeLibrary').onclick=()=>qs('#libraryDrawer').classList.remove('open');qs('#libraryDrawer').onclick=e=>{if(e.target.id==='libraryDrawer')e.currentTarget.classList.remove('open')};qs('#tileScale').oninput=e=>{layout.settings.tileScale=+e.target.value;save();applySettings()};qs('#leftWidth').oninput=e=>{layout.settings.leftWidth=+e.target.value;save();applySettings()};qs('#rightWidth').oninput=e=>{layout.settings.rightWidth=+e.target.value;save();applySettings()};qs('#movePageLeft').onclick=()=>movePage(-1);qs('#movePageRight').onclick=()=>movePage(1);function movePage(delta){const i=layout.pages.findIndex(p=>p.id===current),j=Math.max(0,Math.min(layout.pages.length-1,i+delta));if(i===j)return;const [p]=layout.pages.splice(i,1);layout.pages.splice(j,0,p);save();render()}
qs('#resetLayout').onclick=()=>{layout=clone(DEFAULT_LAYOUT);current=layout.pages[0].id;save();render();renderLibrary()};qs('#exportLayout').onclick=()=>{const blob=new Blob([JSON.stringify(layout,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tagro-irrigation-layout.json';a.click();URL.revokeObjectURL(a.href)};
store.on((_,event)=>{renderContext();if(current==='review'||event.type==='field.set'&&event.payload.path.startsWith('application.'))renderDocks()});
renderLibrary();render();
